// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'G:\A_cloud-note-project\front\ant-design\node_modules\.pnpm\dumi-plugin-color-chunk@1.0.4_dumi@2.3.0-alpha.9\node_modules\dumi-plugin-color-chunk\es\component\index.js';
