// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { scopeIndex as scpi0 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.en-US.md?type=scope-index';
import { scopeIndex as scpi1 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.zh-CN.md?type=scope-index';
import { scopeIndex as scpi2 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.en-US.md?type=scope-index';
import { scopeIndex as scpi3 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.zh-CN.md?type=scope-index';
import { scopeIndex as scpi4 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.en-US.md?type=scope-index';
import { scopeIndex as scpi5 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.zh-CN.md?type=scope-index';
import { scopeIndex as scpi6 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.en-US.md?type=scope-index';
import { scopeIndex as scpi7 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.zh-CN.md?type=scope-index';
import { scopeIndex as scpi8 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.en-US.md?type=scope-index';
import { scopeIndex as scpi9 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.zh-CN.md?type=scope-index';
import { scopeIndex as scpi10 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.en-US.md?type=scope-index';
import { scopeIndex as scpi11 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.zh-CN.md?type=scope-index';
import { scopeIndex as scpi12 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.en-US.md?type=scope-index';
import { scopeIndex as scpi13 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.zh-CN.md?type=scope-index';
import { scopeIndex as scpi14 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.en-US.md?type=scope-index';
import { scopeIndex as scpi15 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.zh-CN.md?type=scope-index';
import { scopeIndex as scpi16 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.en-US.md?type=scope-index';
import { scopeIndex as scpi17 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.zh-CN.md?type=scope-index';
import { scopeIndex as scpi18 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.en-US.md?type=scope-index';
import { scopeIndex as scpi19 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.zh-CN.md?type=scope-index';
import { scopeIndex as scpi20 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.en-US.md?type=scope-index';
import { scopeIndex as scpi21 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.zh-CN.md?type=scope-index';
import { scopeIndex as scpi22 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.en-US.md?type=scope-index';
import { scopeIndex as scpi23 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.zh-CN.md?type=scope-index';
import { scopeIndex as scpi24 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.en-US.md?type=scope-index';
import { scopeIndex as scpi25 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.zh-CN.md?type=scope-index';
import { scopeIndex as scpi26 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.en-US.md?type=scope-index';
import { scopeIndex as scpi27 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.zh-CN.md?type=scope-index';
import { scopeIndex as scpi28 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.en-US.md?type=scope-index';
import { scopeIndex as scpi29 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.zh-CN.md?type=scope-index';
import { scopeIndex as scpi30 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.en-US.md?type=scope-index';
import { scopeIndex as scpi31 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.zh-CN.md?type=scope-index';
import { scopeIndex as scpi32 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.en-US.md?type=scope-index';
import { scopeIndex as scpi33 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.zh-CN.md?type=scope-index';
import { scopeIndex as scpi34 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.en-US.md?type=scope-index';
import { scopeIndex as scpi35 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.zh-CN.md?type=scope-index';
import { scopeIndex as scpi36 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.en-US.md?type=scope-index';
import { scopeIndex as scpi37 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.zh-CN.md?type=scope-index';
import { scopeIndex as scpi38 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.en-US.md?type=scope-index';
import { scopeIndex as scpi39 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.zh-CN.md?type=scope-index';
import { scopeIndex as scpi40 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.en-US.md?type=scope-index';
import { scopeIndex as scpi41 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.zh-CN.md?type=scope-index';
import { scopeIndex as scpi42 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.en-US.md?type=scope-index';
import { scopeIndex as scpi43 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.zh-CN.md?type=scope-index';
import { scopeIndex as scpi44 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.en-US.md?type=scope-index';
import { scopeIndex as scpi45 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.zh-CN.md?type=scope-index';
import { scopeIndex as scpi46 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.en-US.md?type=scope-index';
import { scopeIndex as scpi47 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.zh-CN.md?type=scope-index';
import { scopeIndex as scpi48 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.en-US.md?type=scope-index';
import { scopeIndex as scpi49 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.zh-CN.md?type=scope-index';
import { scopeIndex as scpi50 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.en-US.md?type=scope-index';
import { scopeIndex as scpi51 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.zh-CN.md?type=scope-index';
import { scopeIndex as scpi52 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.en-US.md?type=scope-index';
import { scopeIndex as scpi53 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.zh-CN.md?type=scope-index';
import { scopeIndex as scpi54 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.en-US.md?type=scope-index';
import { scopeIndex as scpi55 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.zh-CN.md?type=scope-index';
import { scopeIndex as scpi56 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.en-US.md?type=scope-index';
import { scopeIndex as scpi57 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.zh-CN.md?type=scope-index';
import { scopeIndex as scpi58 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.en-US.md?type=scope-index';
import { scopeIndex as scpi59 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.zh-CN.md?type=scope-index';
import { scopeIndex as scpi60 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.en-US.md?type=scope-index';
import { scopeIndex as scpi61 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.zh-CN.md?type=scope-index';
import { scopeIndex as scpi62 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.en-US.md?type=scope-index';
import { scopeIndex as scpi63 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.zh-CN.md?type=scope-index';
import { scopeIndex as scpi64 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.en-US.md?type=scope-index';
import { scopeIndex as scpi65 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.zh-CN.md?type=scope-index';
import { scopeIndex as scpi66 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.en-US.md?type=scope-index';
import { scopeIndex as scpi67 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.zh-CN.md?type=scope-index';
import { scopeIndex as scpi68 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.en-US.md?type=scope-index';
import { scopeIndex as scpi69 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.zh-CN.md?type=scope-index';
import { scopeIndex as scpi70 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.en-US.md?type=scope-index';
import { scopeIndex as scpi71 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.zh-CN.md?type=scope-index';
import { scopeIndex as scpi72 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.en-US.md?type=scope-index';
import { scopeIndex as scpi73 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.zh-CN.md?type=scope-index';
import { scopeIndex as scpi74 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.en-US.md?type=scope-index';
import { scopeIndex as scpi75 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.zh-CN.md?type=scope-index';
import { scopeIndex as scpi76 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.en-US.md?type=scope-index';
import { scopeIndex as scpi77 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.zh-CN.md?type=scope-index';
import { scopeIndex as scpi78 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.en-US.md?type=scope-index';
import { scopeIndex as scpi79 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.zh-CN.md?type=scope-index';
import { scopeIndex as scpi80 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.en-US.md?type=scope-index';
import { scopeIndex as scpi81 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.zh-CN.md?type=scope-index';
import { scopeIndex as scpi82 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.en-US.md?type=scope-index';
import { scopeIndex as scpi83 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.zh-CN.md?type=scope-index';
import { scopeIndex as scpi84 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.en-US.md?type=scope-index';
import { scopeIndex as scpi85 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.zh-CN.md?type=scope-index';
import { scopeIndex as scpi86 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.en-US.md?type=scope-index';
import { scopeIndex as scpi87 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.zh-CN.md?type=scope-index';
import { scopeIndex as scpi88 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.en-US.md?type=scope-index';
import { scopeIndex as scpi89 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.zh-CN.md?type=scope-index';
import { scopeIndex as scpi90 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.en-US.md?type=scope-index';
import { scopeIndex as scpi91 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.zh-CN.md?type=scope-index';
import { scopeIndex as scpi92 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.en-US.md?type=scope-index';
import { scopeIndex as scpi93 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.zh-CN.md?type=scope-index';
import { scopeIndex as scpi94 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.en-US.md?type=scope-index';
import { scopeIndex as scpi95 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.zh-CN.md?type=scope-index';
import { scopeIndex as scpi96 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.en-US.md?type=scope-index';
import { scopeIndex as scpi97 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.zh-CN.md?type=scope-index';
import { scopeIndex as scpi98 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.en-US.md?type=scope-index';
import { scopeIndex as scpi99 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.zh-CN.md?type=scope-index';
import { scopeIndex as scpi100 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.en-US.md?type=scope-index';
import { scopeIndex as scpi101 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.zh-CN.md?type=scope-index';
import { scopeIndex as scpi102 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.en-US.md?type=scope-index';
import { scopeIndex as scpi103 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.zh-CN.md?type=scope-index';
import { scopeIndex as scpi104 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.en-US.md?type=scope-index';
import { scopeIndex as scpi105 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.zh-CN.md?type=scope-index';
import { scopeIndex as scpi106 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.en-US.md?type=scope-index';
import { scopeIndex as scpi107 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.zh-CN.md?type=scope-index';
import { scopeIndex as scpi108 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.en-US.md?type=scope-index';
import { scopeIndex as scpi109 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.zh-CN.md?type=scope-index';
import { scopeIndex as scpi110 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.en-US.md?type=scope-index';
import { scopeIndex as scpi111 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.zh-CN.md?type=scope-index';
import { scopeIndex as scpi112 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.en-US.md?type=scope-index';
import { scopeIndex as scpi113 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.zh-CN.md?type=scope-index';
import { scopeIndex as scpi114 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.en-US.md?type=scope-index';
import { scopeIndex as scpi115 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.zh-CN.md?type=scope-index';
import { scopeIndex as scpi116 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.en-US.md?type=scope-index';
import { scopeIndex as scpi117 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.zh-CN.md?type=scope-index';
import { scopeIndex as scpi118 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.en-US.md?type=scope-index';
import { scopeIndex as scpi119 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.zh-CN.md?type=scope-index';
import { scopeIndex as scpi120 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.en-US.md?type=scope-index';
import { scopeIndex as scpi121 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.zh-CN.md?type=scope-index';
import { scopeIndex as scpi122 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.en-US.md?type=scope-index';
import { scopeIndex as scpi123 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.zh-CN.md?type=scope-index';
import { scopeIndex as scpi124 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.en-US.md?type=scope-index';
import { scopeIndex as scpi125 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.zh-CN.md?type=scope-index';
import { scopeIndex as scpi126 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.en-US.md?type=scope-index';
import { scopeIndex as scpi127 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.zh-CN.md?type=scope-index';
import { scopeIndex as scpi128 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.en-US.md?type=scope-index';
import { scopeIndex as scpi129 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.zh-CN.md?type=scope-index';
import { scopeIndex as scpi130 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.en-US.md?type=scope-index';
import { scopeIndex as scpi131 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.zh-CN.md?type=scope-index';
import { scopeIndex as scpi132 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.en-US.md?type=scope-index';
import { scopeIndex as scpi133 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.zh-CN.md?type=scope-index';
import { scopeIndex as scpi134 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.en-US.md?type=scope-index';
import { scopeIndex as scpi135 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.zh-CN.md?type=scope-index';
import { scopeIndex as scpi136 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.en-US.md?type=scope-index';
import { scopeIndex as scpi137 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.zh-CN.md?type=scope-index';
import { scopeIndex as scpi138 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.en-US.md?type=scope-index';
import { scopeIndex as scpi139 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.zh-CN.md?type=scope-index';
import { scopeIndex as scpi140 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.en-US.md?type=scope-index';
import { scopeIndex as scpi141 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.zh-CN.md?type=scope-index';
import { scopeIndex as scpi142 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.en-US.md?type=scope-index';
import { scopeIndex as scpi143 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.zh-CN.md?type=scope-index';
import { scopeIndex as scpi144 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.en-US.md?type=scope-index';
import { scopeIndex as scpi145 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.zh-CN.md?type=scope-index';
import { scopeIndex as scpi146 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.en-US.md?type=scope-index';
import { scopeIndex as scpi147 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.zh-CN.md?type=scope-index';
import { scopeIndex as scpi148 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/values.en-US.md?type=scope-index';
import { scopeIndex as scpi149 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/values.zh-CN.md?type=scope-index';
import { scopeIndex as scpi150 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.en-US.md?type=scope-index';
import { scopeIndex as scpi151 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.zh-CN.md?type=scope-index';
import { scopeIndex as scpi152 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.en-US.md?type=scope-index';
import { scopeIndex as scpi153 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.zh-CN.md?type=scope-index';
import { scopeIndex as scpi154 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.en-US.md?type=scope-index';
import { scopeIndex as scpi155 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.zh-CN.md?type=scope-index';
import { scopeIndex as scpi156 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/faq.en-US.md?type=scope-index';
import { scopeIndex as scpi157 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/faq.zh-CN.md?type=scope-index';
import { scopeIndex as scpi158 } from 'G:/A_cloud-note-project/front/ant-design/docs/resources.en-US.md?type=scope-index';
import { scopeIndex as scpi159 } from 'G:/A_cloud-note-project/front/ant-design/docs/resources.zh-CN.md?type=scope-index';
import { scopeIndex as scpi160 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.en-US.md?type=scope-index';
import { scopeIndex as scpi161 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.zh-CN.md?type=scope-index';
import { scopeIndex as scpi162 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/font.en-US.md?type=scope-index';
import { scopeIndex as scpi163 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/font.zh-CN.md?type=scope-index';
import { scopeIndex as scpi164 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.en-US.md?type=scope-index';
import { scopeIndex as scpi165 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.zh-CN.md?type=scope-index';
import { scopeIndex as scpi166 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.en-US.md?type=scope-index';
import { scopeIndex as scpi167 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.zh-CN.md?type=scope-index';
import { scopeIndex as scpi168 } from 'G:/A_cloud-note-project/front/ant-design/components/affix/index.en-US.md?type=scope-index';
import { scopeIndex as scpi169 } from 'G:/A_cloud-note-project/front/ant-design/components/affix/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi170 } from 'G:/A_cloud-note-project/front/ant-design/components/alert/index.en-US.md?type=scope-index';
import { scopeIndex as scpi171 } from 'G:/A_cloud-note-project/front/ant-design/components/alert/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi172 } from 'G:/A_cloud-note-project/front/ant-design/components/anchor/index.en-US.md?type=scope-index';
import { scopeIndex as scpi173 } from 'G:/A_cloud-note-project/front/ant-design/components/anchor/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi174 } from 'G:/A_cloud-note-project/front/ant-design/components/app/index.en-US.md?type=scope-index';
import { scopeIndex as scpi175 } from 'G:/A_cloud-note-project/front/ant-design/components/app/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi176 } from 'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.en-US.md?type=scope-index';
import { scopeIndex as scpi177 } from 'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi178 } from 'G:/A_cloud-note-project/front/ant-design/components/avatar/index.en-US.md?type=scope-index';
import { scopeIndex as scpi179 } from 'G:/A_cloud-note-project/front/ant-design/components/avatar/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi180 } from 'G:/A_cloud-note-project/front/ant-design/components/badge/index.en-US.md?type=scope-index';
import { scopeIndex as scpi181 } from 'G:/A_cloud-note-project/front/ant-design/components/badge/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi182 } from 'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.en-US.md?type=scope-index';
import { scopeIndex as scpi183 } from 'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi184 } from 'G:/A_cloud-note-project/front/ant-design/components/button/index.en-US.md?type=scope-index';
import { scopeIndex as scpi185 } from 'G:/A_cloud-note-project/front/ant-design/components/button/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi186 } from 'G:/A_cloud-note-project/front/ant-design/components/calendar/index.en-US.md?type=scope-index';
import { scopeIndex as scpi187 } from 'G:/A_cloud-note-project/front/ant-design/components/calendar/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi188 } from 'G:/A_cloud-note-project/front/ant-design/components/card/index.en-US.md?type=scope-index';
import { scopeIndex as scpi189 } from 'G:/A_cloud-note-project/front/ant-design/components/card/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi190 } from 'G:/A_cloud-note-project/front/ant-design/components/carousel/index.en-US.md?type=scope-index';
import { scopeIndex as scpi191 } from 'G:/A_cloud-note-project/front/ant-design/components/carousel/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi192 } from 'G:/A_cloud-note-project/front/ant-design/components/cascader/index.en-US.md?type=scope-index';
import { scopeIndex as scpi193 } from 'G:/A_cloud-note-project/front/ant-design/components/cascader/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi194 } from 'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.en-US.md?type=scope-index';
import { scopeIndex as scpi195 } from 'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi196 } from 'G:/A_cloud-note-project/front/ant-design/components/collapse/index.en-US.md?type=scope-index';
import { scopeIndex as scpi197 } from 'G:/A_cloud-note-project/front/ant-design/components/collapse/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi198 } from 'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.en-US.md?type=scope-index';
import { scopeIndex as scpi199 } from 'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi200 } from 'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.en-US.md?type=scope-index';
import { scopeIndex as scpi201 } from 'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi202 } from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.en-US.md?type=scope-index';
import { scopeIndex as scpi203 } from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi204 } from 'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.en-US.md?type=scope-index';
import { scopeIndex as scpi205 } from 'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi206 } from 'G:/A_cloud-note-project/front/ant-design/components/divider/index.en-US.md?type=scope-index';
import { scopeIndex as scpi207 } from 'G:/A_cloud-note-project/front/ant-design/components/divider/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi208 } from 'G:/A_cloud-note-project/front/ant-design/components/drawer/index.en-US.md?type=scope-index';
import { scopeIndex as scpi209 } from 'G:/A_cloud-note-project/front/ant-design/components/drawer/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi210 } from 'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.en-US.md?type=scope-index';
import { scopeIndex as scpi211 } from 'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi212 } from 'G:/A_cloud-note-project/front/ant-design/components/empty/index.en-US.md?type=scope-index';
import { scopeIndex as scpi213 } from 'G:/A_cloud-note-project/front/ant-design/components/empty/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi214 } from 'G:/A_cloud-note-project/front/ant-design/components/flex/index.en-US.md?type=scope-index';
import { scopeIndex as scpi215 } from 'G:/A_cloud-note-project/front/ant-design/components/flex/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi216 } from 'G:/A_cloud-note-project/front/ant-design/components/float-button/index.en-US.md?type=scope-index';
import { scopeIndex as scpi217 } from 'G:/A_cloud-note-project/front/ant-design/components/float-button/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi218 } from 'G:/A_cloud-note-project/front/ant-design/components/form/index.en-US.md?type=scope-index';
import { scopeIndex as scpi219 } from 'G:/A_cloud-note-project/front/ant-design/components/form/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi220 } from 'G:/A_cloud-note-project/front/ant-design/components/grid/index.en-US.md?type=scope-index';
import { scopeIndex as scpi221 } from 'G:/A_cloud-note-project/front/ant-design/components/grid/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi222 } from 'G:/A_cloud-note-project/front/ant-design/components/icon/index.en-US.md?type=scope-index';
import { scopeIndex as scpi223 } from 'G:/A_cloud-note-project/front/ant-design/components/icon/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi224 } from 'G:/A_cloud-note-project/front/ant-design/components/image/index.en-US.md?type=scope-index';
import { scopeIndex as scpi225 } from 'G:/A_cloud-note-project/front/ant-design/components/image/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi226 } from 'G:/A_cloud-note-project/front/ant-design/components/input-number/index.en-US.md?type=scope-index';
import { scopeIndex as scpi227 } from 'G:/A_cloud-note-project/front/ant-design/components/input-number/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi228 } from 'G:/A_cloud-note-project/front/ant-design/components/input/index.en-US.md?type=scope-index';
import { scopeIndex as scpi229 } from 'G:/A_cloud-note-project/front/ant-design/components/input/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi230 } from 'G:/A_cloud-note-project/front/ant-design/components/layout/index.en-US.md?type=scope-index';
import { scopeIndex as scpi231 } from 'G:/A_cloud-note-project/front/ant-design/components/layout/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi232 } from 'G:/A_cloud-note-project/front/ant-design/components/list/index.en-US.md?type=scope-index';
import { scopeIndex as scpi233 } from 'G:/A_cloud-note-project/front/ant-design/components/list/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi234 } from 'G:/A_cloud-note-project/front/ant-design/components/mentions/index.en-US.md?type=scope-index';
import { scopeIndex as scpi235 } from 'G:/A_cloud-note-project/front/ant-design/components/mentions/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi236 } from 'G:/A_cloud-note-project/front/ant-design/components/menu/index.en-US.md?type=scope-index';
import { scopeIndex as scpi237 } from 'G:/A_cloud-note-project/front/ant-design/components/menu/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi238 } from 'G:/A_cloud-note-project/front/ant-design/components/message/index.en-US.md?type=scope-index';
import { scopeIndex as scpi239 } from 'G:/A_cloud-note-project/front/ant-design/components/message/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi240 } from 'G:/A_cloud-note-project/front/ant-design/components/modal/index.en-US.md?type=scope-index';
import { scopeIndex as scpi241 } from 'G:/A_cloud-note-project/front/ant-design/components/modal/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi242 } from 'G:/A_cloud-note-project/front/ant-design/components/notification/index.en-US.md?type=scope-index';
import { scopeIndex as scpi243 } from 'G:/A_cloud-note-project/front/ant-design/components/notification/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi244 } from 'G:/A_cloud-note-project/front/ant-design/components/overview/index.en-US.md?type=scope-index';
import { scopeIndex as scpi245 } from 'G:/A_cloud-note-project/front/ant-design/components/overview/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi246 } from 'G:/A_cloud-note-project/front/ant-design/components/pagination/index.en-US.md?type=scope-index';
import { scopeIndex as scpi247 } from 'G:/A_cloud-note-project/front/ant-design/components/pagination/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi248 } from 'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.en-US.md?type=scope-index';
import { scopeIndex as scpi249 } from 'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi250 } from 'G:/A_cloud-note-project/front/ant-design/components/popover/index.en-US.md?type=scope-index';
import { scopeIndex as scpi251 } from 'G:/A_cloud-note-project/front/ant-design/components/popover/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi252 } from 'G:/A_cloud-note-project/front/ant-design/components/progress/index.en-US.md?type=scope-index';
import { scopeIndex as scpi253 } from 'G:/A_cloud-note-project/front/ant-design/components/progress/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi254 } from 'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.en-US.md?type=scope-index';
import { scopeIndex as scpi255 } from 'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi256 } from 'G:/A_cloud-note-project/front/ant-design/components/radio/index.en-US.md?type=scope-index';
import { scopeIndex as scpi257 } from 'G:/A_cloud-note-project/front/ant-design/components/radio/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi258 } from 'G:/A_cloud-note-project/front/ant-design/components/rate/index.en-US.md?type=scope-index';
import { scopeIndex as scpi259 } from 'G:/A_cloud-note-project/front/ant-design/components/rate/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi260 } from 'G:/A_cloud-note-project/front/ant-design/components/result/index.en-US.md?type=scope-index';
import { scopeIndex as scpi261 } from 'G:/A_cloud-note-project/front/ant-design/components/result/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi262 } from 'G:/A_cloud-note-project/front/ant-design/components/segmented/index.en-US.md?type=scope-index';
import { scopeIndex as scpi263 } from 'G:/A_cloud-note-project/front/ant-design/components/segmented/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi264 } from 'G:/A_cloud-note-project/front/ant-design/components/select/index.en-US.md?type=scope-index';
import { scopeIndex as scpi265 } from 'G:/A_cloud-note-project/front/ant-design/components/select/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi266 } from 'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.en-US.md?type=scope-index';
import { scopeIndex as scpi267 } from 'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi268 } from 'G:/A_cloud-note-project/front/ant-design/components/slider/index.en-US.md?type=scope-index';
import { scopeIndex as scpi269 } from 'G:/A_cloud-note-project/front/ant-design/components/slider/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi270 } from 'G:/A_cloud-note-project/front/ant-design/components/space/index.en-US.md?type=scope-index';
import { scopeIndex as scpi271 } from 'G:/A_cloud-note-project/front/ant-design/components/space/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi272 } from 'G:/A_cloud-note-project/front/ant-design/components/spin/index.en-US.md?type=scope-index';
import { scopeIndex as scpi273 } from 'G:/A_cloud-note-project/front/ant-design/components/spin/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi274 } from 'G:/A_cloud-note-project/front/ant-design/components/statistic/index.en-US.md?type=scope-index';
import { scopeIndex as scpi275 } from 'G:/A_cloud-note-project/front/ant-design/components/statistic/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi276 } from 'G:/A_cloud-note-project/front/ant-design/components/steps/index.en-US.md?type=scope-index';
import { scopeIndex as scpi277 } from 'G:/A_cloud-note-project/front/ant-design/components/steps/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi278 } from 'G:/A_cloud-note-project/front/ant-design/components/switch/index.en-US.md?type=scope-index';
import { scopeIndex as scpi279 } from 'G:/A_cloud-note-project/front/ant-design/components/switch/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi280 } from 'G:/A_cloud-note-project/front/ant-design/components/table/index.en-US.md?type=scope-index';
import { scopeIndex as scpi281 } from 'G:/A_cloud-note-project/front/ant-design/components/table/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi282 } from 'G:/A_cloud-note-project/front/ant-design/components/tabs/index.en-US.md?type=scope-index';
import { scopeIndex as scpi283 } from 'G:/A_cloud-note-project/front/ant-design/components/tabs/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi284 } from 'G:/A_cloud-note-project/front/ant-design/components/tag/index.en-US.md?type=scope-index';
import { scopeIndex as scpi285 } from 'G:/A_cloud-note-project/front/ant-design/components/tag/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi286 } from 'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.en-US.md?type=scope-index';
import { scopeIndex as scpi287 } from 'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi288 } from 'G:/A_cloud-note-project/front/ant-design/components/timeline/index.en-US.md?type=scope-index';
import { scopeIndex as scpi289 } from 'G:/A_cloud-note-project/front/ant-design/components/timeline/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi290 } from 'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.en-US.md?type=scope-index';
import { scopeIndex as scpi291 } from 'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi292 } from 'G:/A_cloud-note-project/front/ant-design/components/tour/index.en-US.md?type=scope-index';
import { scopeIndex as scpi293 } from 'G:/A_cloud-note-project/front/ant-design/components/tour/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi294 } from 'G:/A_cloud-note-project/front/ant-design/components/transfer/index.en-US.md?type=scope-index';
import { scopeIndex as scpi295 } from 'G:/A_cloud-note-project/front/ant-design/components/transfer/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi296 } from 'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.en-US.md?type=scope-index';
import { scopeIndex as scpi297 } from 'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi298 } from 'G:/A_cloud-note-project/front/ant-design/components/tree/index.en-US.md?type=scope-index';
import { scopeIndex as scpi299 } from 'G:/A_cloud-note-project/front/ant-design/components/tree/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi300 } from 'G:/A_cloud-note-project/front/ant-design/components/typography/index.en-US.md?type=scope-index';
import { scopeIndex as scpi301 } from 'G:/A_cloud-note-project/front/ant-design/components/typography/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi302 } from 'G:/A_cloud-note-project/front/ant-design/components/upload/index.en-US.md?type=scope-index';
import { scopeIndex as scpi303 } from 'G:/A_cloud-note-project/front/ant-design/components/upload/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi304 } from 'G:/A_cloud-note-project/front/ant-design/components/watermark/index.en-US.md?type=scope-index';
import { scopeIndex as scpi305 } from 'G:/A_cloud-note-project/front/ant-design/components/watermark/index.zh-CN.md?type=scope-index';
import { scopeIndex as scpi306 } from 'G:/A_cloud-note-project/front/ant-design/CHANGELOG.zh-CN.md?type=scope-index';
import { scopeIndex as scpi307 } from 'G:/A_cloud-note-project/front/ant-design/CHANGELOG.en-US.md?type=scope-index';

const scopeIndexes: Record<string, { ids: string[], getter: () => Promise<any> }> = {
  ...scpi0,
  ...scpi1,
  ...scpi2,
  ...scpi3,
  ...scpi4,
  ...scpi5,
  ...scpi6,
  ...scpi7,
  ...scpi8,
  ...scpi9,
  ...scpi10,
  ...scpi11,
  ...scpi12,
  ...scpi13,
  ...scpi14,
  ...scpi15,
  ...scpi16,
  ...scpi17,
  ...scpi18,
  ...scpi19,
  ...scpi20,
  ...scpi21,
  ...scpi22,
  ...scpi23,
  ...scpi24,
  ...scpi25,
  ...scpi26,
  ...scpi27,
  ...scpi28,
  ...scpi29,
  ...scpi30,
  ...scpi31,
  ...scpi32,
  ...scpi33,
  ...scpi34,
  ...scpi35,
  ...scpi36,
  ...scpi37,
  ...scpi38,
  ...scpi39,
  ...scpi40,
  ...scpi41,
  ...scpi42,
  ...scpi43,
  ...scpi44,
  ...scpi45,
  ...scpi46,
  ...scpi47,
  ...scpi48,
  ...scpi49,
  ...scpi50,
  ...scpi51,
  ...scpi52,
  ...scpi53,
  ...scpi54,
  ...scpi55,
  ...scpi56,
  ...scpi57,
  ...scpi58,
  ...scpi59,
  ...scpi60,
  ...scpi61,
  ...scpi62,
  ...scpi63,
  ...scpi64,
  ...scpi65,
  ...scpi66,
  ...scpi67,
  ...scpi68,
  ...scpi69,
  ...scpi70,
  ...scpi71,
  ...scpi72,
  ...scpi73,
  ...scpi74,
  ...scpi75,
  ...scpi76,
  ...scpi77,
  ...scpi78,
  ...scpi79,
  ...scpi80,
  ...scpi81,
  ...scpi82,
  ...scpi83,
  ...scpi84,
  ...scpi85,
  ...scpi86,
  ...scpi87,
  ...scpi88,
  ...scpi89,
  ...scpi90,
  ...scpi91,
  ...scpi92,
  ...scpi93,
  ...scpi94,
  ...scpi95,
  ...scpi96,
  ...scpi97,
  ...scpi98,
  ...scpi99,
  ...scpi100,
  ...scpi101,
  ...scpi102,
  ...scpi103,
  ...scpi104,
  ...scpi105,
  ...scpi106,
  ...scpi107,
  ...scpi108,
  ...scpi109,
  ...scpi110,
  ...scpi111,
  ...scpi112,
  ...scpi113,
  ...scpi114,
  ...scpi115,
  ...scpi116,
  ...scpi117,
  ...scpi118,
  ...scpi119,
  ...scpi120,
  ...scpi121,
  ...scpi122,
  ...scpi123,
  ...scpi124,
  ...scpi125,
  ...scpi126,
  ...scpi127,
  ...scpi128,
  ...scpi129,
  ...scpi130,
  ...scpi131,
  ...scpi132,
  ...scpi133,
  ...scpi134,
  ...scpi135,
  ...scpi136,
  ...scpi137,
  ...scpi138,
  ...scpi139,
  ...scpi140,
  ...scpi141,
  ...scpi142,
  ...scpi143,
  ...scpi144,
  ...scpi145,
  ...scpi146,
  ...scpi147,
  ...scpi148,
  ...scpi149,
  ...scpi150,
  ...scpi151,
  ...scpi152,
  ...scpi153,
  ...scpi154,
  ...scpi155,
  ...scpi156,
  ...scpi157,
  ...scpi158,
  ...scpi159,
  ...scpi160,
  ...scpi161,
  ...scpi162,
  ...scpi163,
  ...scpi164,
  ...scpi165,
  ...scpi166,
  ...scpi167,
  ...scpi168,
  ...scpi169,
  ...scpi170,
  ...scpi171,
  ...scpi172,
  ...scpi173,
  ...scpi174,
  ...scpi175,
  ...scpi176,
  ...scpi177,
  ...scpi178,
  ...scpi179,
  ...scpi180,
  ...scpi181,
  ...scpi182,
  ...scpi183,
  ...scpi184,
  ...scpi185,
  ...scpi186,
  ...scpi187,
  ...scpi188,
  ...scpi189,
  ...scpi190,
  ...scpi191,
  ...scpi192,
  ...scpi193,
  ...scpi194,
  ...scpi195,
  ...scpi196,
  ...scpi197,
  ...scpi198,
  ...scpi199,
  ...scpi200,
  ...scpi201,
  ...scpi202,
  ...scpi203,
  ...scpi204,
  ...scpi205,
  ...scpi206,
  ...scpi207,
  ...scpi208,
  ...scpi209,
  ...scpi210,
  ...scpi211,
  ...scpi212,
  ...scpi213,
  ...scpi214,
  ...scpi215,
  ...scpi216,
  ...scpi217,
  ...scpi218,
  ...scpi219,
  ...scpi220,
  ...scpi221,
  ...scpi222,
  ...scpi223,
  ...scpi224,
  ...scpi225,
  ...scpi226,
  ...scpi227,
  ...scpi228,
  ...scpi229,
  ...scpi230,
  ...scpi231,
  ...scpi232,
  ...scpi233,
  ...scpi234,
  ...scpi235,
  ...scpi236,
  ...scpi237,
  ...scpi238,
  ...scpi239,
  ...scpi240,
  ...scpi241,
  ...scpi242,
  ...scpi243,
  ...scpi244,
  ...scpi245,
  ...scpi246,
  ...scpi247,
  ...scpi248,
  ...scpi249,
  ...scpi250,
  ...scpi251,
  ...scpi252,
  ...scpi253,
  ...scpi254,
  ...scpi255,
  ...scpi256,
  ...scpi257,
  ...scpi258,
  ...scpi259,
  ...scpi260,
  ...scpi261,
  ...scpi262,
  ...scpi263,
  ...scpi264,
  ...scpi265,
  ...scpi266,
  ...scpi267,
  ...scpi268,
  ...scpi269,
  ...scpi270,
  ...scpi271,
  ...scpi272,
  ...scpi273,
  ...scpi274,
  ...scpi275,
  ...scpi276,
  ...scpi277,
  ...scpi278,
  ...scpi279,
  ...scpi280,
  ...scpi281,
  ...scpi282,
  ...scpi283,
  ...scpi284,
  ...scpi285,
  ...scpi286,
  ...scpi287,
  ...scpi288,
  ...scpi289,
  ...scpi290,
  ...scpi291,
  ...scpi292,
  ...scpi293,
  ...scpi294,
  ...scpi295,
  ...scpi296,
  ...scpi297,
  ...scpi298,
  ...scpi299,
  ...scpi300,
  ...scpi301,
  ...scpi302,
  ...scpi303,
  ...scpi304,
  ...scpi305,
  ...scpi306,
  ...scpi307,
};

/** Async to load demo by id */
export const getDemoScopesById = async (id: string) => {
  const getter = scopeIndexes[id];

  if (!getter) {
    return {};
  }

  const { scopes }: any = await getter() || {};

  return scopes?.[id] || {};
};
