// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports';
export * from 'G:/A_cloud-note-project/front/ant-design/node_modules/dumi/dist/client/theme-api/index.js';
export { getRouteMetaById } from './meta/route-meta';
export { loadFilesMeta } from './meta/search';
export { getDemoScopesById } from './live/demo-scopes';
