// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
// @umijs/renderer-*
export {
  Helmet,
  HelmetProvider,
  Link,
  NavLink,
  Navigate,
  Outlet,
  __getRoot,
  __useFetcher,
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  matchPath,
  matchRoutes,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/node_modules/@umijs/renderer-react';
export type { History } from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { createHistory, history } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export {
  ApplyPluginsType,
  PluginManager,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/node_modules/umi/client/client/plugin.js';
export const useServerInsertedHTML: Function = () => {};
// plugins
export {
  Access,
  useAccess,
  useAccessMarkedRoutes,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-access';
export {
  FormattedDate,
  FormattedDateParts,
  FormattedDisplayName,
  FormattedHTMLMessage,
  FormattedList,
  FormattedMessage,
  FormattedNumber,
  FormattedNumberParts,
  FormattedPlural,
  FormattedRelativeTime,
  FormattedTime,
  FormattedTimeParts,
  IntlProvider,
  RawIntlProvider,
  SelectLang,
  addLocale,
  formatMessage,
  getAllLocales,
  getIntl,
  getLocale,
  injectIntl,
  setLocale,
  useIntl,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-locale';
export {
  Provider,
  useModel,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-model';
export {
  UseRequestProvider,
  getRequestInstance,
  request,
  useRequest,
} from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-access/types.d';
export * from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-antd/types.d';
export * from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-layout/types.d';
export * from 'G:/A_cloud-note-project/front/app-crm-minimal/myapp/src/.umi/plugin-request/types.d';
