// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { tabs } from './tabs';
import { filesFrontmatter } from './frontmatter';

const files = {
  'docs/blog/contributor-development-maintenance-guide.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.en-US.md?type=text'),
  },
  'docs/blog/contributor-development-maintenance-guide.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.zh-CN.md?type=text'),
  },
  'docs/spec/research-message-and-feedback.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.en-US.md?type=text'),
  },
  'docs/spec/research-message-and-feedback.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.zh-CN.md?type=text'),
  },
  'docs/react/use-with-create-react-app.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.en-US.md?type=text'),
  },
  'docs/react/use-with-create-react-app.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.zh-CN.md?type=text'),
  },
  'docs/react/use-custom-date-library.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.en-US.md?type=text'),
  },
  'docs/react/use-custom-date-library.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.zh-CN.md?type=text'),
  },
  'docs/blog/github-actions-workflow.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.en-US.md?type=text'),
  },
  'docs/blog/github-actions-workflow.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.zh-CN.md?type=text'),
  },
  'docs/react/migrate-less-variables.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.en-US.md?type=text'),
  },
  'docs/react/migrate-less-variables.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.zh-CN.md?type=text'),
  },
  'docs/react/server-side-rendering.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.en-US.md?type=text'),
  },
  'docs/react/server-side-rendering.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.zh-CN.md?type=text'),
  },
  'docs/blog/config-provider-style.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.en-US.md?type=text'),
  },
  'docs/blog/config-provider-style.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.zh-CN.md?type=text'),
  },
  'docs/spec/research-navigation.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.en-US.md?type=text'),
  },
  'docs/spec/research-navigation.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.zh-CN.md?type=text'),
  },
  'docs/blog/mock-project-build.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.en-US.md?type=text'),
  },
  'docs/blog/mock-project-build.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.zh-CN.md?type=text'),
  },
  'docs/blog/notification-stack.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.en-US.md?type=text'),
  },
  'docs/blog/notification-stack.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.zh-CN.md?type=text'),
  },
  'docs/blog/to-be-collaborator.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.en-US.md?type=text'),
  },
  'docs/blog/to-be-collaborator.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.zh-CN.md?type=text'),
  },
  'docs/blog/to-be-what-you-see.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.en-US.md?type=text'),
  },
  'docs/blog/to-be-what-you-see.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.zh-CN.md?type=text'),
  },
  'docs/spec/research-exception.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.en-US.md?type=text'),
  },
  'docs/spec/research-exception.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.zh-CN.md?type=text'),
  },
  'docs/spec/research-workbench.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.en-US.md?type=text'),
  },
  'docs/spec/research-workbench.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.zh-CN.md?type=text'),
  },
  'docs/spec/visualization-page.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.en-US.md?type=text'),
  },
  'docs/spec/visualization-page.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.zh-CN.md?type=text'),
  },
  'docs/react/compatible-style.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.en-US.md?type=text'),
  },
  'docs/react/compatible-style.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.zh-CN.md?type=text'),
  },
  'docs/spec/research-overview.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.en-US.md?type=text'),
  },
  'docs/spec/research-overview.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.zh-CN.md?type=text'),
  },
  'docs/blog/modal-hook-order.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.en-US.md?type=text'),
  },
  'docs/blog/modal-hook-order.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.zh-CN.md?type=text'),
  },
  'docs/react/customize-theme.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.en-US.md?type=text'),
  },
  'docs/react/customize-theme.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.zh-CN.md?type=text'),
  },
  'docs/react/getting-started.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.en-US.md?type=text'),
  },
  'docs/react/getting-started.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.zh-CN.md?type=text'),
  },
  'docs/blog/historical-debt.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.en-US.md?type=text'),
  },
  'docs/blog/historical-debt.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.zh-CN.md?type=text'),
  },
  'docs/blog/hydrate-cssinjs.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.en-US.md?type=text'),
  },
  'docs/blog/hydrate-cssinjs.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.zh-CN.md?type=text'),
  },
  'docs/blog/testing-migrate.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.en-US.md?type=text'),
  },
  'docs/blog/testing-migrate.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.zh-CN.md?type=text'),
  },
  'docs/react/recommendation.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.en-US.md?type=text'),
  },
  'docs/react/recommendation.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.zh-CN.md?type=text'),
  },
  'docs/spec/research-result.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.en-US.md?type=text'),
  },
  'docs/spec/research-result.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.zh-CN.md?type=text'),
  },
  'docs/blog/why-not-static.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.en-US.md?type=text'),
  },
  'docs/blog/why-not-static.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.zh-CN.md?type=text'),
  },
  'docs/react/use-with-next.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.en-US.md?type=text'),
  },
  'docs/react/use-with-next.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.zh-CN.md?type=text'),
  },
  'docs/react/use-with-vite.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.en-US.md?type=text'),
  },
  'docs/react/use-with-vite.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.zh-CN.md?type=text'),
  },
  'docs/spec/research-empty.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.en-US.md?type=text'),
  },
  'docs/spec/research-empty.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.zh-CN.md?type=text'),
  },
  'docs/blog/check-conduct.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.en-US.md?type=text'),
  },
  'docs/blog/check-conduct.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.zh-CN.md?type=text'),
  },
  'docs/blog/tooltip-align.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.en-US.md?type=text'),
  },
  'docs/blog/tooltip-align.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.zh-CN.md?type=text'),
  },
  'docs/blog/virtual-table.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.en-US.md?type=text'),
  },
  'docs/blog/virtual-table.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.zh-CN.md?type=text'),
  },
  'docs/react/common-props.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.en-US.md?type=text'),
  },
  'docs/react/common-props.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.zh-CN.md?type=text'),
  },
  'docs/react/contributing.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.en-US.md?type=text'),
  },
  'docs/react/contributing.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.zh-CN.md?type=text'),
  },
  'docs/react/migration-v5.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.en-US.md?type=text'),
  },
  'docs/react/migration-v5.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.zh-CN.md?type=text'),
  },
  'docs/react/use-with-umi.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.en-US.md?type=text'),
  },
  'docs/react/use-with-umi.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.zh-CN.md?type=text'),
  },
  'docs/spec/research-form.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.en-US.md?type=text'),
  },
  'docs/spec/research-form.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.zh-CN.md?type=text'),
  },
  'docs/spec/research-list.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.en-US.md?type=text'),
  },
  'docs/spec/research-list.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.zh-CN.md?type=text'),
  },
  'docs/blog/color-picker.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.en-US.md?type=text'),
  },
  'docs/blog/color-picker.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.zh-CN.md?type=text'),
  },
  'docs/blog/getContainer.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.en-US.md?type=text'),
  },
  'docs/blog/getContainer.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.zh-CN.md?type=text'),
  },
  'docs/blog/issue-helper.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.en-US.md?type=text'),
  },
  'docs/blog/issue-helper.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.zh-CN.md?type=text'),
  },
  'docs/blog/render-times.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.en-US.md?type=text'),
  },
  'docs/blog/render-times.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.zh-CN.md?type=text'),
  },
  'docs/blog/tree-shaking.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.en-US.md?type=text'),
  },
  'docs/blog/tree-shaking.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.zh-CN.md?type=text'),
  },
  'docs/spec/data-display.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.en-US.md?type=text'),
  },
  'docs/spec/data-display.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.zh-CN.md?type=text'),
  },
  'docs/spec/illustration.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.en-US.md?type=text'),
  },
  'docs/spec/illustration.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.zh-CN.md?type=text'),
  },
  'docs/blog/extract-ssr.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.en-US.md?type=text'),
  },
  'docs/blog/extract-ssr.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.zh-CN.md?type=text'),
  },
  'docs/spec/copywriting.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.en-US.md?type=text'),
  },
  'docs/spec/copywriting.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.zh-CN.md?type=text'),
  },
  'docs/spec/data-format.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.en-US.md?type=text'),
  },
  'docs/spec/data-format.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.zh-CN.md?type=text'),
  },
  'docs/spec/detail-page.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.en-US.md?type=text'),
  },
  'docs/spec/detail-page.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.zh-CN.md?type=text'),
  },
  'docs/spec/lightweight.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.en-US.md?type=text'),
  },
  'docs/spec/lightweight.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.zh-CN.md?type=text'),
  },
  'docs/blog/happy-work.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.en-US.md?type=text'),
  },
  'docs/blog/happy-work.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.zh-CN.md?type=text'),
  },
  'docs/react/introduce.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.en-US.md?type=text'),
  },
  'docs/react/introduce.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.zh-CN.md?type=text'),
  },
  'docs/spec/data-entry.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.en-US.md?type=text'),
  },
  'docs/spec/data-entry.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.zh-CN.md?type=text'),
  },
  'docs/spec/invitation.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.en-US.md?type=text'),
  },
  'docs/spec/invitation.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.zh-CN.md?type=text'),
  },
  'docs/spec/navigation.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.en-US.md?type=text'),
  },
  'docs/spec/navigation.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.zh-CN.md?type=text'),
  },
  'docs/spec/repetition.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.en-US.md?type=text'),
  },
  'docs/spec/repetition.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.zh-CN.md?type=text'),
  },
  'docs/spec/transition.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.en-US.md?type=text'),
  },
  'docs/spec/transition.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.zh-CN.md?type=text'),
  },
  'docs/blog/css-in-js.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.en-US.md?type=text'),
  },
  'docs/blog/css-in-js.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.zh-CN.md?type=text'),
  },
  'docs/spec/alignment.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.en-US.md?type=text'),
  },
  'docs/spec/alignment.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.zh-CN.md?type=text'),
  },
  'docs/spec/data-list.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.en-US.md?type=text'),
  },
  'docs/spec/data-list.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.zh-CN.md?type=text'),
  },
  'docs/spec/introduce.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.en-US.md?type=text'),
  },
  'docs/spec/introduce.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.zh-CN.md?type=text'),
  },
  'docs/spec/proximity.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.en-US.md?type=text'),
  },
  'docs/spec/proximity.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.zh-CN.md?type=text'),
  },
  'docs/blog/suspense.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.en-US.md?type=text'),
  },
  'docs/blog/suspense.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.zh-CN.md?type=text'),
  },
  'docs/spec/contrast.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.en-US.md?type=text'),
  },
  'docs/spec/contrast.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.zh-CN.md?type=text'),
  },
  'docs/spec/feedback.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.en-US.md?type=text'),
  },
  'docs/spec/feedback.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.zh-CN.md?type=text'),
  },
  'docs/spec/overview.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.en-US.md?type=text'),
  },
  'docs/spec/overview.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.zh-CN.md?type=text'),
  },
  'docs/spec/reaction.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.en-US.md?type=text'),
  },
  'docs/spec/reaction.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.zh-CN.md?type=text'),
  },
  'docs/spec/buttons.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.en-US.md?type=text'),
  },
  'docs/spec/buttons.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.zh-CN.md?type=text'),
  },
  'docs/spec/colors.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.en-US.md?type=text'),
  },
  'docs/spec/colors.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.zh-CN.md?type=text'),
  },
  'docs/spec/direct.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.en-US.md?type=text'),
  },
  'docs/spec/direct.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.zh-CN.md?type=text'),
  },
  'docs/spec/layout.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.en-US.md?type=text'),
  },
  'docs/spec/layout.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.zh-CN.md?type=text'),
  },
  'docs/spec/motion.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.en-US.md?type=text'),
  },
  'docs/spec/motion.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.zh-CN.md?type=text'),
  },
  'docs/spec/shadow.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.en-US.md?type=text'),
  },
  'docs/spec/shadow.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.zh-CN.md?type=text'),
  },
  'docs/spec/values.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/values.en-US.md?type=text'),
  },
  'docs/spec/values.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/values.zh-CN.md?type=text'),
  },
  'docs/spec/visual.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.en-US.md?type=text'),
  },
  'docs/spec/visual.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.zh-CN.md?type=text'),
  },
  'docs/react/i18n.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.en-US.md?type=text'),
  },
  'docs/react/i18n.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.zh-CN.md?type=text'),
  },
  'docs/spec/cases.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.en-US.md?type=text'),
  },
  'docs/spec/cases.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.zh-CN.md?type=text'),
  },
  'docs/react/faq.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/react/faq.en-US.md?type=text'),
  },
  'docs/react/faq.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/react/faq.zh-CN.md?type=text'),
  },
  'docs/resources.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/resources.en-US.md?type=text'),
  },
  'docs/resources.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/resources.zh-CN.md?type=text'),
  },
  'docs/spec/dark.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.en-US.md?type=text'),
  },
  'docs/spec/dark.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.zh-CN.md?type=text'),
  },
  'docs/spec/font.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/font.en-US.md?type=text'),
  },
  'docs/spec/font.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/font.zh-CN.md?type=text'),
  },
  'docs/spec/icon.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.en-US.md?type=text'),
  },
  'docs/spec/icon.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.zh-CN.md?type=text'),
  },
  'docs/spec/stay.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__en-US" */'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.en-US.md?type=text'),
  },
  'docs/spec/stay.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.zh-CN.md?type=text'),
  },
  'components/affix/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/affix/index.en-US.md?type=text'),
  },
  'components/affix/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/affix/index.zh-CN.md?type=text'),
  },
  'components/alert/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/alert/index.en-US.md?type=text'),
  },
  'components/alert/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/alert/index.zh-CN.md?type=text'),
  },
  'components/anchor/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/anchor/index.en-US.md?type=text'),
  },
  'components/anchor/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/anchor/index.zh-CN.md?type=text'),
  },
  'components/app/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/app/index.en-US.md?type=text'),
  },
  'components/app/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/app/index.zh-CN.md?type=text'),
  },
  'components/auto-complete/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.en-US.md?type=text'),
  },
  'components/auto-complete/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.zh-CN.md?type=text'),
  },
  'components/avatar/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/avatar/index.en-US.md?type=text'),
  },
  'components/avatar/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/avatar/index.zh-CN.md?type=text'),
  },
  'components/badge/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/badge/index.en-US.md?type=text'),
  },
  'components/badge/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/badge/index.zh-CN.md?type=text'),
  },
  'components/breadcrumb/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.en-US.md?type=text'),
  },
  'components/breadcrumb/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.zh-CN.md?type=text'),
  },
  'components/button/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/button/index.en-US.md?type=text'),
  },
  'components/button/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/button/index.zh-CN.md?type=text'),
  },
  'components/calendar/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/calendar/index.en-US.md?type=text'),
  },
  'components/calendar/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/calendar/index.zh-CN.md?type=text'),
  },
  'components/card/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/card/index.en-US.md?type=text'),
  },
  'components/card/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/card/index.zh-CN.md?type=text'),
  },
  'components/carousel/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/carousel/index.en-US.md?type=text'),
  },
  'components/carousel/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/carousel/index.zh-CN.md?type=text'),
  },
  'components/cascader/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/cascader/index.en-US.md?type=text'),
  },
  'components/cascader/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/cascader/index.zh-CN.md?type=text'),
  },
  'components/checkbox/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.en-US.md?type=text'),
  },
  'components/checkbox/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.zh-CN.md?type=text'),
  },
  'components/collapse/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/collapse/index.en-US.md?type=text'),
  },
  'components/collapse/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/collapse/index.zh-CN.md?type=text'),
  },
  'components/color-picker/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.en-US.md?type=text'),
  },
  'components/color-picker/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.zh-CN.md?type=text'),
  },
  'components/config-provider/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.en-US.md?type=text'),
  },
  'components/config-provider/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.zh-CN.md?type=text'),
  },
  'components/date-picker/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.en-US.md?type=text'),
  },
  'components/date-picker/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.zh-CN.md?type=text'),
    tabs: ["components/date-picker/index.$tab-design.zh-CN"],
  },
  'components/descriptions/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.en-US.md?type=text'),
  },
  'components/descriptions/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.zh-CN.md?type=text'),
  },
  'components/divider/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/divider/index.en-US.md?type=text'),
  },
  'components/divider/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/divider/index.zh-CN.md?type=text'),
  },
  'components/drawer/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/drawer/index.en-US.md?type=text'),
  },
  'components/drawer/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/drawer/index.zh-CN.md?type=text'),
  },
  'components/dropdown/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.en-US.md?type=text'),
  },
  'components/dropdown/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.zh-CN.md?type=text'),
  },
  'components/empty/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/empty/index.en-US.md?type=text'),
  },
  'components/empty/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/empty/index.zh-CN.md?type=text'),
  },
  'components/flex/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/flex/index.en-US.md?type=text'),
  },
  'components/flex/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/flex/index.zh-CN.md?type=text'),
  },
  'components/float-button/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/float-button/index.en-US.md?type=text'),
  },
  'components/float-button/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/float-button/index.zh-CN.md?type=text'),
  },
  'components/form/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/form/index.en-US.md?type=text'),
  },
  'components/form/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/form/index.zh-CN.md?type=text'),
  },
  'components/grid/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/grid/index.en-US.md?type=text'),
  },
  'components/grid/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/grid/index.zh-CN.md?type=text'),
  },
  'components/icon/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/icon/index.en-US.md?type=text'),
  },
  'components/icon/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/icon/index.zh-CN.md?type=text'),
  },
  'components/image/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/image/index.en-US.md?type=text'),
  },
  'components/image/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/image/index.zh-CN.md?type=text'),
  },
  'components/input-number/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/input-number/index.en-US.md?type=text'),
  },
  'components/input-number/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/input-number/index.zh-CN.md?type=text'),
  },
  'components/input/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/input/index.en-US.md?type=text'),
  },
  'components/input/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/input/index.zh-CN.md?type=text'),
  },
  'components/layout/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/layout/index.en-US.md?type=text'),
  },
  'components/layout/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/layout/index.zh-CN.md?type=text'),
  },
  'components/list/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/list/index.en-US.md?type=text'),
  },
  'components/list/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/list/index.zh-CN.md?type=text'),
  },
  'components/mentions/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/mentions/index.en-US.md?type=text'),
  },
  'components/mentions/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/mentions/index.zh-CN.md?type=text'),
  },
  'components/menu/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/menu/index.en-US.md?type=text'),
  },
  'components/menu/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/menu/index.zh-CN.md?type=text'),
  },
  'components/message/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/message/index.en-US.md?type=text'),
  },
  'components/message/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/message/index.zh-CN.md?type=text'),
  },
  'components/modal/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/modal/index.en-US.md?type=text'),
  },
  'components/modal/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/modal/index.zh-CN.md?type=text'),
  },
  'components/notification/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/notification/index.en-US.md?type=text'),
  },
  'components/notification/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/notification/index.zh-CN.md?type=text'),
  },
  'components/overview/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/overview/index.en-US.md?type=text'),
  },
  'components/overview/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/overview/index.zh-CN.md?type=text'),
  },
  'components/pagination/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/pagination/index.en-US.md?type=text'),
  },
  'components/pagination/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/pagination/index.zh-CN.md?type=text'),
  },
  'components/popconfirm/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.en-US.md?type=text'),
  },
  'components/popconfirm/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.zh-CN.md?type=text'),
  },
  'components/popover/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/popover/index.en-US.md?type=text'),
  },
  'components/popover/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/popover/index.zh-CN.md?type=text'),
  },
  'components/progress/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/progress/index.en-US.md?type=text'),
  },
  'components/progress/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/progress/index.zh-CN.md?type=text'),
  },
  'components/qr-code/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.en-US.md?type=text'),
  },
  'components/qr-code/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.zh-CN.md?type=text'),
  },
  'components/radio/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/radio/index.en-US.md?type=text'),
  },
  'components/radio/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/radio/index.zh-CN.md?type=text'),
  },
  'components/rate/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/rate/index.en-US.md?type=text'),
  },
  'components/rate/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/rate/index.zh-CN.md?type=text'),
  },
  'components/result/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/result/index.en-US.md?type=text'),
  },
  'components/result/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/result/index.zh-CN.md?type=text'),
  },
  'components/segmented/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/segmented/index.en-US.md?type=text'),
  },
  'components/segmented/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/segmented/index.zh-CN.md?type=text'),
  },
  'components/select/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/select/index.en-US.md?type=text'),
  },
  'components/select/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/select/index.zh-CN.md?type=text'),
  },
  'components/skeleton/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.en-US.md?type=text'),
  },
  'components/skeleton/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.zh-CN.md?type=text'),
  },
  'components/slider/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/slider/index.en-US.md?type=text'),
  },
  'components/slider/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/slider/index.zh-CN.md?type=text'),
  },
  'components/space/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/space/index.en-US.md?type=text'),
  },
  'components/space/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/space/index.zh-CN.md?type=text'),
  },
  'components/spin/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/spin/index.en-US.md?type=text'),
  },
  'components/spin/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/spin/index.zh-CN.md?type=text'),
  },
  'components/statistic/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/statistic/index.en-US.md?type=text'),
  },
  'components/statistic/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/statistic/index.zh-CN.md?type=text'),
  },
  'components/steps/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/steps/index.en-US.md?type=text'),
  },
  'components/steps/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/steps/index.zh-CN.md?type=text'),
  },
  'components/switch/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/switch/index.en-US.md?type=text'),
  },
  'components/switch/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/switch/index.zh-CN.md?type=text'),
  },
  'components/table/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/table/index.en-US.md?type=text'),
  },
  'components/table/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/table/index.zh-CN.md?type=text'),
  },
  'components/tabs/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tabs/index.en-US.md?type=text'),
  },
  'components/tabs/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tabs/index.zh-CN.md?type=text'),
  },
  'components/tag/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tag/index.en-US.md?type=text'),
  },
  'components/tag/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tag/index.zh-CN.md?type=text'),
  },
  'components/time-picker/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.en-US.md?type=text'),
  },
  'components/time-picker/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.zh-CN.md?type=text'),
  },
  'components/timeline/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/timeline/index.en-US.md?type=text'),
  },
  'components/timeline/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/timeline/index.zh-CN.md?type=text'),
  },
  'components/tooltip/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.en-US.md?type=text'),
  },
  'components/tooltip/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.zh-CN.md?type=text'),
  },
  'components/tour/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tour/index.en-US.md?type=text'),
  },
  'components/tour/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tour/index.zh-CN.md?type=text'),
  },
  'components/transfer/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/transfer/index.en-US.md?type=text'),
  },
  'components/transfer/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/transfer/index.zh-CN.md?type=text'),
  },
  'components/tree-select/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.en-US.md?type=text'),
  },
  'components/tree-select/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.zh-CN.md?type=text'),
  },
  'components/tree/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/tree/index.en-US.md?type=text'),
  },
  'components/tree/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/tree/index.zh-CN.md?type=text'),
  },
  'components/typography/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/typography/index.en-US.md?type=text'),
  },
  'components/typography/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/typography/index.zh-CN.md?type=text'),
  },
  'components/upload/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/upload/index.en-US.md?type=text'),
  },
  'components/upload/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/upload/index.zh-CN.md?type=text'),
  },
  'components/watermark/index.en-US': {
    textGetter: () => import(/* webpackChunkName: "meta__components__en-US" */'G:/A_cloud-note-project/front/ant-design/components/watermark/index.en-US.md?type=text'),
  },
  'components/watermark/index.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/watermark/index.zh-CN.md?type=text'),
  },
  'changelog-cn': {
    textGetter: () => import(/* webpackChunkName: "meta__CHANGELOG.zh-CN.md__zh-CN" */'G:/A_cloud-note-project/front/ant-design/CHANGELOG.zh-CN.md?type=text'),
  },
  'changelog': {
    textGetter: () => import(/* webpackChunkName: "meta__CHANGELOG.en-US.md__en-US" */'G:/A_cloud-note-project/front/ant-design/CHANGELOG.en-US.md?type=text'),
  },
  'components/date-picker/index.$tab-design.zh-CN': {
    textGetter: () => import(/* webpackChunkName: "meta__components__zh-CN" */'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.$tab-design.zh-CN.md?type=text'),
  },
};

export const getRouteMetaById = async (id: string) => {
  const file = files[id];

  if (!file) {
    return null;
  }

  const text = await file.textGetter();
  const frontmatter = filesFrontmatter[id];

  const tabsMeta = file.tabs && await Promise.all(file.tabs.map(async (tab) => {
    const meta = await getRouteMetaById(tab) ?? {
      frontmatter: { title: tabs[tab].title },
      toc: [],
      texts: [],
    };
    return {
      ...tabs[tab],
      meta,
    }
  }));

  return {
    texts: text?.texts,
    toc: text?.toc,
    frontmatter,
    tabs: tabsMeta,
  };
}
