// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demoIndex as dmi4 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.en-US.md?type=demo-index';
import { demoIndex as dmi5 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/contributor-development-maintenance-guide.zh-CN.md?type=demo-index';
import { demoIndex as dmi6 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.en-US.md?type=demo-index';
import { demoIndex as dmi7 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-message-and-feedback.zh-CN.md?type=demo-index';
import { demoIndex as dmi8 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.en-US.md?type=demo-index';
import { demoIndex as dmi9 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-create-react-app.zh-CN.md?type=demo-index';
import { demoIndex as dmi10 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.en-US.md?type=demo-index';
import { demoIndex as dmi11 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-custom-date-library.zh-CN.md?type=demo-index';
import { demoIndex as dmi12 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.en-US.md?type=demo-index';
import { demoIndex as dmi13 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/github-actions-workflow.zh-CN.md?type=demo-index';
import { demoIndex as dmi14 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.en-US.md?type=demo-index';
import { demoIndex as dmi15 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migrate-less-variables.zh-CN.md?type=demo-index';
import { demoIndex as dmi16 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.en-US.md?type=demo-index';
import { demoIndex as dmi17 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/server-side-rendering.zh-CN.md?type=demo-index';
import { demoIndex as dmi18 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.en-US.md?type=demo-index';
import { demoIndex as dmi19 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/config-provider-style.zh-CN.md?type=demo-index';
import { demoIndex as dmi20 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.en-US.md?type=demo-index';
import { demoIndex as dmi21 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-navigation.zh-CN.md?type=demo-index';
import { demoIndex as dmi22 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.en-US.md?type=demo-index';
import { demoIndex as dmi23 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/mock-project-build.zh-CN.md?type=demo-index';
import { demoIndex as dmi24 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.en-US.md?type=demo-index';
import { demoIndex as dmi25 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/notification-stack.zh-CN.md?type=demo-index';
import { demoIndex as dmi26 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.en-US.md?type=demo-index';
import { demoIndex as dmi27 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-collaborator.zh-CN.md?type=demo-index';
import { demoIndex as dmi28 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.en-US.md?type=demo-index';
import { demoIndex as dmi29 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/to-be-what-you-see.zh-CN.md?type=demo-index';
import { demoIndex as dmi30 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.en-US.md?type=demo-index';
import { demoIndex as dmi31 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-exception.zh-CN.md?type=demo-index';
import { demoIndex as dmi32 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.en-US.md?type=demo-index';
import { demoIndex as dmi33 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-workbench.zh-CN.md?type=demo-index';
import { demoIndex as dmi34 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.en-US.md?type=demo-index';
import { demoIndex as dmi35 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visualization-page.zh-CN.md?type=demo-index';
import { demoIndex as dmi36 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.en-US.md?type=demo-index';
import { demoIndex as dmi37 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/compatible-style.zh-CN.md?type=demo-index';
import { demoIndex as dmi38 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.en-US.md?type=demo-index';
import { demoIndex as dmi39 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-overview.zh-CN.md?type=demo-index';
import { demoIndex as dmi40 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.en-US.md?type=demo-index';
import { demoIndex as dmi41 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/modal-hook-order.zh-CN.md?type=demo-index';
import { demoIndex as dmi42 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.en-US.md?type=demo-index';
import { demoIndex as dmi43 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/customize-theme.zh-CN.md?type=demo-index';
import { demoIndex as dmi44 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.en-US.md?type=demo-index';
import { demoIndex as dmi45 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/getting-started.zh-CN.md?type=demo-index';
import { demoIndex as dmi46 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.en-US.md?type=demo-index';
import { demoIndex as dmi47 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/historical-debt.zh-CN.md?type=demo-index';
import { demoIndex as dmi48 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.en-US.md?type=demo-index';
import { demoIndex as dmi49 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/hydrate-cssinjs.zh-CN.md?type=demo-index';
import { demoIndex as dmi50 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.en-US.md?type=demo-index';
import { demoIndex as dmi51 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/testing-migrate.zh-CN.md?type=demo-index';
import { demoIndex as dmi52 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.en-US.md?type=demo-index';
import { demoIndex as dmi53 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/recommendation.zh-CN.md?type=demo-index';
import { demoIndex as dmi54 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.en-US.md?type=demo-index';
import { demoIndex as dmi55 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-result.zh-CN.md?type=demo-index';
import { demoIndex as dmi56 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.en-US.md?type=demo-index';
import { demoIndex as dmi57 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/why-not-static.zh-CN.md?type=demo-index';
import { demoIndex as dmi58 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.en-US.md?type=demo-index';
import { demoIndex as dmi59 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-next.zh-CN.md?type=demo-index';
import { demoIndex as dmi60 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.en-US.md?type=demo-index';
import { demoIndex as dmi61 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-vite.zh-CN.md?type=demo-index';
import { demoIndex as dmi62 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.en-US.md?type=demo-index';
import { demoIndex as dmi63 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-empty.zh-CN.md?type=demo-index';
import { demoIndex as dmi64 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.en-US.md?type=demo-index';
import { demoIndex as dmi65 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/check-conduct.zh-CN.md?type=demo-index';
import { demoIndex as dmi66 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.en-US.md?type=demo-index';
import { demoIndex as dmi67 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tooltip-align.zh-CN.md?type=demo-index';
import { demoIndex as dmi68 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.en-US.md?type=demo-index';
import { demoIndex as dmi69 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/virtual-table.zh-CN.md?type=demo-index';
import { demoIndex as dmi70 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.en-US.md?type=demo-index';
import { demoIndex as dmi71 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/common-props.zh-CN.md?type=demo-index';
import { demoIndex as dmi72 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.en-US.md?type=demo-index';
import { demoIndex as dmi73 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/contributing.zh-CN.md?type=demo-index';
import { demoIndex as dmi74 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.en-US.md?type=demo-index';
import { demoIndex as dmi75 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/migration-v5.zh-CN.md?type=demo-index';
import { demoIndex as dmi76 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.en-US.md?type=demo-index';
import { demoIndex as dmi77 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/use-with-umi.zh-CN.md?type=demo-index';
import { demoIndex as dmi78 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.en-US.md?type=demo-index';
import { demoIndex as dmi79 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-form.zh-CN.md?type=demo-index';
import { demoIndex as dmi80 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.en-US.md?type=demo-index';
import { demoIndex as dmi81 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/research-list.zh-CN.md?type=demo-index';
import { demoIndex as dmi82 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.en-US.md?type=demo-index';
import { demoIndex as dmi83 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/color-picker.zh-CN.md?type=demo-index';
import { demoIndex as dmi84 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.en-US.md?type=demo-index';
import { demoIndex as dmi85 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/getContainer.zh-CN.md?type=demo-index';
import { demoIndex as dmi86 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.en-US.md?type=demo-index';
import { demoIndex as dmi87 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/issue-helper.zh-CN.md?type=demo-index';
import { demoIndex as dmi88 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.en-US.md?type=demo-index';
import { demoIndex as dmi89 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/render-times.zh-CN.md?type=demo-index';
import { demoIndex as dmi90 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.en-US.md?type=demo-index';
import { demoIndex as dmi91 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/tree-shaking.zh-CN.md?type=demo-index';
import { demoIndex as dmi92 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.en-US.md?type=demo-index';
import { demoIndex as dmi93 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-display.zh-CN.md?type=demo-index';
import { demoIndex as dmi94 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.en-US.md?type=demo-index';
import { demoIndex as dmi95 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/illustration.zh-CN.md?type=demo-index';
import { demoIndex as dmi96 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.en-US.md?type=demo-index';
import { demoIndex as dmi97 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/extract-ssr.zh-CN.md?type=demo-index';
import { demoIndex as dmi98 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.en-US.md?type=demo-index';
import { demoIndex as dmi99 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/copywriting.zh-CN.md?type=demo-index';
import { demoIndex as dmi100 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.en-US.md?type=demo-index';
import { demoIndex as dmi101 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-format.zh-CN.md?type=demo-index';
import { demoIndex as dmi102 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.en-US.md?type=demo-index';
import { demoIndex as dmi103 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/detail-page.zh-CN.md?type=demo-index';
import { demoIndex as dmi104 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.en-US.md?type=demo-index';
import { demoIndex as dmi105 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/lightweight.zh-CN.md?type=demo-index';
import { demoIndex as dmi106 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.en-US.md?type=demo-index';
import { demoIndex as dmi107 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/happy-work.zh-CN.md?type=demo-index';
import { demoIndex as dmi108 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.en-US.md?type=demo-index';
import { demoIndex as dmi109 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/introduce.zh-CN.md?type=demo-index';
import { demoIndex as dmi110 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.en-US.md?type=demo-index';
import { demoIndex as dmi111 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-entry.zh-CN.md?type=demo-index';
import { demoIndex as dmi112 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.en-US.md?type=demo-index';
import { demoIndex as dmi113 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/invitation.zh-CN.md?type=demo-index';
import { demoIndex as dmi114 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.en-US.md?type=demo-index';
import { demoIndex as dmi115 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/navigation.zh-CN.md?type=demo-index';
import { demoIndex as dmi116 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.en-US.md?type=demo-index';
import { demoIndex as dmi117 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/repetition.zh-CN.md?type=demo-index';
import { demoIndex as dmi118 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.en-US.md?type=demo-index';
import { demoIndex as dmi119 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/transition.zh-CN.md?type=demo-index';
import { demoIndex as dmi120 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.en-US.md?type=demo-index';
import { demoIndex as dmi121 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/css-in-js.zh-CN.md?type=demo-index';
import { demoIndex as dmi122 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.en-US.md?type=demo-index';
import { demoIndex as dmi123 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/alignment.zh-CN.md?type=demo-index';
import { demoIndex as dmi124 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.en-US.md?type=demo-index';
import { demoIndex as dmi125 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/data-list.zh-CN.md?type=demo-index';
import { demoIndex as dmi126 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.en-US.md?type=demo-index';
import { demoIndex as dmi127 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/introduce.zh-CN.md?type=demo-index';
import { demoIndex as dmi128 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.en-US.md?type=demo-index';
import { demoIndex as dmi129 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/proximity.zh-CN.md?type=demo-index';
import { demoIndex as dmi130 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.en-US.md?type=demo-index';
import { demoIndex as dmi131 } from 'G:/A_cloud-note-project/front/ant-design/docs/blog/suspense.zh-CN.md?type=demo-index';
import { demoIndex as dmi132 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.en-US.md?type=demo-index';
import { demoIndex as dmi133 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/contrast.zh-CN.md?type=demo-index';
import { demoIndex as dmi134 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.en-US.md?type=demo-index';
import { demoIndex as dmi135 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/feedback.zh-CN.md?type=demo-index';
import { demoIndex as dmi136 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.en-US.md?type=demo-index';
import { demoIndex as dmi137 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/overview.zh-CN.md?type=demo-index';
import { demoIndex as dmi138 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.en-US.md?type=demo-index';
import { demoIndex as dmi139 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/reaction.zh-CN.md?type=demo-index';
import { demoIndex as dmi140 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.en-US.md?type=demo-index';
import { demoIndex as dmi141 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/buttons.zh-CN.md?type=demo-index';
import { demoIndex as dmi142 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.en-US.md?type=demo-index';
import { demoIndex as dmi143 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/colors.zh-CN.md?type=demo-index';
import { demoIndex as dmi144 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.en-US.md?type=demo-index';
import { demoIndex as dmi145 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/direct.zh-CN.md?type=demo-index';
import { demoIndex as dmi146 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.en-US.md?type=demo-index';
import { demoIndex as dmi147 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/layout.zh-CN.md?type=demo-index';
import { demoIndex as dmi148 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.en-US.md?type=demo-index';
import { demoIndex as dmi149 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/motion.zh-CN.md?type=demo-index';
import { demoIndex as dmi150 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.en-US.md?type=demo-index';
import { demoIndex as dmi151 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/shadow.zh-CN.md?type=demo-index';
import { demoIndex as dmi152 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/values.en-US.md?type=demo-index';
import { demoIndex as dmi153 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/values.zh-CN.md?type=demo-index';
import { demoIndex as dmi154 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.en-US.md?type=demo-index';
import { demoIndex as dmi155 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/visual.zh-CN.md?type=demo-index';
import { demoIndex as dmi156 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.en-US.md?type=demo-index';
import { demoIndex as dmi157 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/i18n.zh-CN.md?type=demo-index';
import { demoIndex as dmi158 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.en-US.md?type=demo-index';
import { demoIndex as dmi159 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/cases.zh-CN.md?type=demo-index';
import { demoIndex as dmi160 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/faq.en-US.md?type=demo-index';
import { demoIndex as dmi161 } from 'G:/A_cloud-note-project/front/ant-design/docs/react/faq.zh-CN.md?type=demo-index';
import { demoIndex as dmi162 } from 'G:/A_cloud-note-project/front/ant-design/docs/resources.en-US.md?type=demo-index';
import { demoIndex as dmi163 } from 'G:/A_cloud-note-project/front/ant-design/docs/resources.zh-CN.md?type=demo-index';
import { demoIndex as dmi164 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.en-US.md?type=demo-index';
import { demoIndex as dmi165 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/dark.zh-CN.md?type=demo-index';
import { demoIndex as dmi166 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/font.en-US.md?type=demo-index';
import { demoIndex as dmi167 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/font.zh-CN.md?type=demo-index';
import { demoIndex as dmi168 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.en-US.md?type=demo-index';
import { demoIndex as dmi169 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/icon.zh-CN.md?type=demo-index';
import { demoIndex as dmi170 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.en-US.md?type=demo-index';
import { demoIndex as dmi171 } from 'G:/A_cloud-note-project/front/ant-design/docs/spec/stay.zh-CN.md?type=demo-index';
import { demoIndex as dmi172 } from 'G:/A_cloud-note-project/front/ant-design/components/affix/index.en-US.md?type=demo-index';
import { demoIndex as dmi173 } from 'G:/A_cloud-note-project/front/ant-design/components/affix/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi174 } from 'G:/A_cloud-note-project/front/ant-design/components/alert/index.en-US.md?type=demo-index';
import { demoIndex as dmi175 } from 'G:/A_cloud-note-project/front/ant-design/components/alert/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi176 } from 'G:/A_cloud-note-project/front/ant-design/components/anchor/index.en-US.md?type=demo-index';
import { demoIndex as dmi177 } from 'G:/A_cloud-note-project/front/ant-design/components/anchor/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi178 } from 'G:/A_cloud-note-project/front/ant-design/components/app/index.en-US.md?type=demo-index';
import { demoIndex as dmi179 } from 'G:/A_cloud-note-project/front/ant-design/components/app/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi180 } from 'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.en-US.md?type=demo-index';
import { demoIndex as dmi181 } from 'G:/A_cloud-note-project/front/ant-design/components/auto-complete/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi182 } from 'G:/A_cloud-note-project/front/ant-design/components/avatar/index.en-US.md?type=demo-index';
import { demoIndex as dmi183 } from 'G:/A_cloud-note-project/front/ant-design/components/avatar/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi184 } from 'G:/A_cloud-note-project/front/ant-design/components/badge/index.en-US.md?type=demo-index';
import { demoIndex as dmi185 } from 'G:/A_cloud-note-project/front/ant-design/components/badge/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi186 } from 'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.en-US.md?type=demo-index';
import { demoIndex as dmi187 } from 'G:/A_cloud-note-project/front/ant-design/components/breadcrumb/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi188 } from 'G:/A_cloud-note-project/front/ant-design/components/button/index.en-US.md?type=demo-index';
import { demoIndex as dmi189 } from 'G:/A_cloud-note-project/front/ant-design/components/button/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi190 } from 'G:/A_cloud-note-project/front/ant-design/components/calendar/index.en-US.md?type=demo-index';
import { demoIndex as dmi191 } from 'G:/A_cloud-note-project/front/ant-design/components/calendar/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi192 } from 'G:/A_cloud-note-project/front/ant-design/components/card/index.en-US.md?type=demo-index';
import { demoIndex as dmi193 } from 'G:/A_cloud-note-project/front/ant-design/components/card/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi194 } from 'G:/A_cloud-note-project/front/ant-design/components/carousel/index.en-US.md?type=demo-index';
import { demoIndex as dmi195 } from 'G:/A_cloud-note-project/front/ant-design/components/carousel/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi196 } from 'G:/A_cloud-note-project/front/ant-design/components/cascader/index.en-US.md?type=demo-index';
import { demoIndex as dmi197 } from 'G:/A_cloud-note-project/front/ant-design/components/cascader/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi198 } from 'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.en-US.md?type=demo-index';
import { demoIndex as dmi199 } from 'G:/A_cloud-note-project/front/ant-design/components/checkbox/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi200 } from 'G:/A_cloud-note-project/front/ant-design/components/collapse/index.en-US.md?type=demo-index';
import { demoIndex as dmi201 } from 'G:/A_cloud-note-project/front/ant-design/components/collapse/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi202 } from 'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.en-US.md?type=demo-index';
import { demoIndex as dmi203 } from 'G:/A_cloud-note-project/front/ant-design/components/color-picker/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi204 } from 'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.en-US.md?type=demo-index';
import { demoIndex as dmi205 } from 'G:/A_cloud-note-project/front/ant-design/components/config-provider/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi206 } from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.en-US.md?type=demo-index';
import { demoIndex as dmi207 } from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi208 } from 'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.en-US.md?type=demo-index';
import { demoIndex as dmi209 } from 'G:/A_cloud-note-project/front/ant-design/components/descriptions/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi210 } from 'G:/A_cloud-note-project/front/ant-design/components/divider/index.en-US.md?type=demo-index';
import { demoIndex as dmi211 } from 'G:/A_cloud-note-project/front/ant-design/components/divider/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi212 } from 'G:/A_cloud-note-project/front/ant-design/components/drawer/index.en-US.md?type=demo-index';
import { demoIndex as dmi213 } from 'G:/A_cloud-note-project/front/ant-design/components/drawer/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi214 } from 'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.en-US.md?type=demo-index';
import { demoIndex as dmi215 } from 'G:/A_cloud-note-project/front/ant-design/components/dropdown/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi216 } from 'G:/A_cloud-note-project/front/ant-design/components/empty/index.en-US.md?type=demo-index';
import { demoIndex as dmi217 } from 'G:/A_cloud-note-project/front/ant-design/components/empty/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi218 } from 'G:/A_cloud-note-project/front/ant-design/components/flex/index.en-US.md?type=demo-index';
import { demoIndex as dmi219 } from 'G:/A_cloud-note-project/front/ant-design/components/flex/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi220 } from 'G:/A_cloud-note-project/front/ant-design/components/float-button/index.en-US.md?type=demo-index';
import { demoIndex as dmi221 } from 'G:/A_cloud-note-project/front/ant-design/components/float-button/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi222 } from 'G:/A_cloud-note-project/front/ant-design/components/form/index.en-US.md?type=demo-index';
import { demoIndex as dmi223 } from 'G:/A_cloud-note-project/front/ant-design/components/form/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi224 } from 'G:/A_cloud-note-project/front/ant-design/components/grid/index.en-US.md?type=demo-index';
import { demoIndex as dmi225 } from 'G:/A_cloud-note-project/front/ant-design/components/grid/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi226 } from 'G:/A_cloud-note-project/front/ant-design/components/icon/index.en-US.md?type=demo-index';
import { demoIndex as dmi227 } from 'G:/A_cloud-note-project/front/ant-design/components/icon/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi228 } from 'G:/A_cloud-note-project/front/ant-design/components/image/index.en-US.md?type=demo-index';
import { demoIndex as dmi229 } from 'G:/A_cloud-note-project/front/ant-design/components/image/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi230 } from 'G:/A_cloud-note-project/front/ant-design/components/input-number/index.en-US.md?type=demo-index';
import { demoIndex as dmi231 } from 'G:/A_cloud-note-project/front/ant-design/components/input-number/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi232 } from 'G:/A_cloud-note-project/front/ant-design/components/input/index.en-US.md?type=demo-index';
import { demoIndex as dmi233 } from 'G:/A_cloud-note-project/front/ant-design/components/input/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi234 } from 'G:/A_cloud-note-project/front/ant-design/components/layout/index.en-US.md?type=demo-index';
import { demoIndex as dmi235 } from 'G:/A_cloud-note-project/front/ant-design/components/layout/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi236 } from 'G:/A_cloud-note-project/front/ant-design/components/list/index.en-US.md?type=demo-index';
import { demoIndex as dmi237 } from 'G:/A_cloud-note-project/front/ant-design/components/list/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi238 } from 'G:/A_cloud-note-project/front/ant-design/components/mentions/index.en-US.md?type=demo-index';
import { demoIndex as dmi239 } from 'G:/A_cloud-note-project/front/ant-design/components/mentions/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi240 } from 'G:/A_cloud-note-project/front/ant-design/components/menu/index.en-US.md?type=demo-index';
import { demoIndex as dmi241 } from 'G:/A_cloud-note-project/front/ant-design/components/menu/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi242 } from 'G:/A_cloud-note-project/front/ant-design/components/message/index.en-US.md?type=demo-index';
import { demoIndex as dmi243 } from 'G:/A_cloud-note-project/front/ant-design/components/message/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi244 } from 'G:/A_cloud-note-project/front/ant-design/components/modal/index.en-US.md?type=demo-index';
import { demoIndex as dmi245 } from 'G:/A_cloud-note-project/front/ant-design/components/modal/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi246 } from 'G:/A_cloud-note-project/front/ant-design/components/notification/index.en-US.md?type=demo-index';
import { demoIndex as dmi247 } from 'G:/A_cloud-note-project/front/ant-design/components/notification/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi248 } from 'G:/A_cloud-note-project/front/ant-design/components/overview/index.en-US.md?type=demo-index';
import { demoIndex as dmi249 } from 'G:/A_cloud-note-project/front/ant-design/components/overview/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi250 } from 'G:/A_cloud-note-project/front/ant-design/components/pagination/index.en-US.md?type=demo-index';
import { demoIndex as dmi251 } from 'G:/A_cloud-note-project/front/ant-design/components/pagination/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi252 } from 'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.en-US.md?type=demo-index';
import { demoIndex as dmi253 } from 'G:/A_cloud-note-project/front/ant-design/components/popconfirm/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi254 } from 'G:/A_cloud-note-project/front/ant-design/components/popover/index.en-US.md?type=demo-index';
import { demoIndex as dmi255 } from 'G:/A_cloud-note-project/front/ant-design/components/popover/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi256 } from 'G:/A_cloud-note-project/front/ant-design/components/progress/index.en-US.md?type=demo-index';
import { demoIndex as dmi257 } from 'G:/A_cloud-note-project/front/ant-design/components/progress/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi258 } from 'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.en-US.md?type=demo-index';
import { demoIndex as dmi259 } from 'G:/A_cloud-note-project/front/ant-design/components/qr-code/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi260 } from 'G:/A_cloud-note-project/front/ant-design/components/radio/index.en-US.md?type=demo-index';
import { demoIndex as dmi261 } from 'G:/A_cloud-note-project/front/ant-design/components/radio/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi262 } from 'G:/A_cloud-note-project/front/ant-design/components/rate/index.en-US.md?type=demo-index';
import { demoIndex as dmi263 } from 'G:/A_cloud-note-project/front/ant-design/components/rate/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi264 } from 'G:/A_cloud-note-project/front/ant-design/components/result/index.en-US.md?type=demo-index';
import { demoIndex as dmi265 } from 'G:/A_cloud-note-project/front/ant-design/components/result/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi266 } from 'G:/A_cloud-note-project/front/ant-design/components/segmented/index.en-US.md?type=demo-index';
import { demoIndex as dmi267 } from 'G:/A_cloud-note-project/front/ant-design/components/segmented/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi268 } from 'G:/A_cloud-note-project/front/ant-design/components/select/index.en-US.md?type=demo-index';
import { demoIndex as dmi269 } from 'G:/A_cloud-note-project/front/ant-design/components/select/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi270 } from 'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.en-US.md?type=demo-index';
import { demoIndex as dmi271 } from 'G:/A_cloud-note-project/front/ant-design/components/skeleton/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi272 } from 'G:/A_cloud-note-project/front/ant-design/components/slider/index.en-US.md?type=demo-index';
import { demoIndex as dmi273 } from 'G:/A_cloud-note-project/front/ant-design/components/slider/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi274 } from 'G:/A_cloud-note-project/front/ant-design/components/space/index.en-US.md?type=demo-index';
import { demoIndex as dmi275 } from 'G:/A_cloud-note-project/front/ant-design/components/space/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi276 } from 'G:/A_cloud-note-project/front/ant-design/components/spin/index.en-US.md?type=demo-index';
import { demoIndex as dmi277 } from 'G:/A_cloud-note-project/front/ant-design/components/spin/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi278 } from 'G:/A_cloud-note-project/front/ant-design/components/statistic/index.en-US.md?type=demo-index';
import { demoIndex as dmi279 } from 'G:/A_cloud-note-project/front/ant-design/components/statistic/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi280 } from 'G:/A_cloud-note-project/front/ant-design/components/steps/index.en-US.md?type=demo-index';
import { demoIndex as dmi281 } from 'G:/A_cloud-note-project/front/ant-design/components/steps/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi282 } from 'G:/A_cloud-note-project/front/ant-design/components/switch/index.en-US.md?type=demo-index';
import { demoIndex as dmi283 } from 'G:/A_cloud-note-project/front/ant-design/components/switch/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi284 } from 'G:/A_cloud-note-project/front/ant-design/components/table/index.en-US.md?type=demo-index';
import { demoIndex as dmi285 } from 'G:/A_cloud-note-project/front/ant-design/components/table/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi286 } from 'G:/A_cloud-note-project/front/ant-design/components/tabs/index.en-US.md?type=demo-index';
import { demoIndex as dmi287 } from 'G:/A_cloud-note-project/front/ant-design/components/tabs/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi288 } from 'G:/A_cloud-note-project/front/ant-design/components/tag/index.en-US.md?type=demo-index';
import { demoIndex as dmi289 } from 'G:/A_cloud-note-project/front/ant-design/components/tag/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi290 } from 'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.en-US.md?type=demo-index';
import { demoIndex as dmi291 } from 'G:/A_cloud-note-project/front/ant-design/components/time-picker/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi292 } from 'G:/A_cloud-note-project/front/ant-design/components/timeline/index.en-US.md?type=demo-index';
import { demoIndex as dmi293 } from 'G:/A_cloud-note-project/front/ant-design/components/timeline/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi294 } from 'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.en-US.md?type=demo-index';
import { demoIndex as dmi295 } from 'G:/A_cloud-note-project/front/ant-design/components/tooltip/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi296 } from 'G:/A_cloud-note-project/front/ant-design/components/tour/index.en-US.md?type=demo-index';
import { demoIndex as dmi297 } from 'G:/A_cloud-note-project/front/ant-design/components/tour/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi298 } from 'G:/A_cloud-note-project/front/ant-design/components/transfer/index.en-US.md?type=demo-index';
import { demoIndex as dmi299 } from 'G:/A_cloud-note-project/front/ant-design/components/transfer/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi300 } from 'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.en-US.md?type=demo-index';
import { demoIndex as dmi301 } from 'G:/A_cloud-note-project/front/ant-design/components/tree-select/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi302 } from 'G:/A_cloud-note-project/front/ant-design/components/tree/index.en-US.md?type=demo-index';
import { demoIndex as dmi303 } from 'G:/A_cloud-note-project/front/ant-design/components/tree/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi304 } from 'G:/A_cloud-note-project/front/ant-design/components/typography/index.en-US.md?type=demo-index';
import { demoIndex as dmi305 } from 'G:/A_cloud-note-project/front/ant-design/components/typography/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi306 } from 'G:/A_cloud-note-project/front/ant-design/components/upload/index.en-US.md?type=demo-index';
import { demoIndex as dmi307 } from 'G:/A_cloud-note-project/front/ant-design/components/upload/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi308 } from 'G:/A_cloud-note-project/front/ant-design/components/watermark/index.en-US.md?type=demo-index';
import { demoIndex as dmi309 } from 'G:/A_cloud-note-project/front/ant-design/components/watermark/index.zh-CN.md?type=demo-index';
import { demoIndex as dmi310 } from 'G:/A_cloud-note-project/front/ant-design/CHANGELOG.zh-CN.md?type=demo-index';
import { demoIndex as dmi311 } from 'G:/A_cloud-note-project/front/ant-design/CHANGELOG.en-US.md?type=demo-index';
import { demoIndex as dmi312 } from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.$tab-design.zh-CN.md?type=demo-index';

export const demoIndexes: Record<string, { ids: string[], getter: () => Promise<any> }> = {
  'docs/blog/contributor-development-maintenance-guide.en-US': dmi4,
  'docs/blog/contributor-development-maintenance-guide.zh-CN': dmi5,
  'docs/spec/research-message-and-feedback.en-US': dmi6,
  'docs/spec/research-message-and-feedback.zh-CN': dmi7,
  'docs/react/use-with-create-react-app.en-US': dmi8,
  'docs/react/use-with-create-react-app.zh-CN': dmi9,
  'docs/react/use-custom-date-library.en-US': dmi10,
  'docs/react/use-custom-date-library.zh-CN': dmi11,
  'docs/blog/github-actions-workflow.en-US': dmi12,
  'docs/blog/github-actions-workflow.zh-CN': dmi13,
  'docs/react/migrate-less-variables.en-US': dmi14,
  'docs/react/migrate-less-variables.zh-CN': dmi15,
  'docs/react/server-side-rendering.en-US': dmi16,
  'docs/react/server-side-rendering.zh-CN': dmi17,
  'docs/blog/config-provider-style.en-US': dmi18,
  'docs/blog/config-provider-style.zh-CN': dmi19,
  'docs/spec/research-navigation.en-US': dmi20,
  'docs/spec/research-navigation.zh-CN': dmi21,
  'docs/blog/mock-project-build.en-US': dmi22,
  'docs/blog/mock-project-build.zh-CN': dmi23,
  'docs/blog/notification-stack.en-US': dmi24,
  'docs/blog/notification-stack.zh-CN': dmi25,
  'docs/blog/to-be-collaborator.en-US': dmi26,
  'docs/blog/to-be-collaborator.zh-CN': dmi27,
  'docs/blog/to-be-what-you-see.en-US': dmi28,
  'docs/blog/to-be-what-you-see.zh-CN': dmi29,
  'docs/spec/research-exception.en-US': dmi30,
  'docs/spec/research-exception.zh-CN': dmi31,
  'docs/spec/research-workbench.en-US': dmi32,
  'docs/spec/research-workbench.zh-CN': dmi33,
  'docs/spec/visualization-page.en-US': dmi34,
  'docs/spec/visualization-page.zh-CN': dmi35,
  'docs/react/compatible-style.en-US': dmi36,
  'docs/react/compatible-style.zh-CN': dmi37,
  'docs/spec/research-overview.en-US': dmi38,
  'docs/spec/research-overview.zh-CN': dmi39,
  'docs/blog/modal-hook-order.en-US': dmi40,
  'docs/blog/modal-hook-order.zh-CN': dmi41,
  'docs/react/customize-theme.en-US': dmi42,
  'docs/react/customize-theme.zh-CN': dmi43,
  'docs/react/getting-started.en-US': dmi44,
  'docs/react/getting-started.zh-CN': dmi45,
  'docs/blog/historical-debt.en-US': dmi46,
  'docs/blog/historical-debt.zh-CN': dmi47,
  'docs/blog/hydrate-cssinjs.en-US': dmi48,
  'docs/blog/hydrate-cssinjs.zh-CN': dmi49,
  'docs/blog/testing-migrate.en-US': dmi50,
  'docs/blog/testing-migrate.zh-CN': dmi51,
  'docs/react/recommendation.en-US': dmi52,
  'docs/react/recommendation.zh-CN': dmi53,
  'docs/spec/research-result.en-US': dmi54,
  'docs/spec/research-result.zh-CN': dmi55,
  'docs/blog/why-not-static.en-US': dmi56,
  'docs/blog/why-not-static.zh-CN': dmi57,
  'docs/react/use-with-next.en-US': dmi58,
  'docs/react/use-with-next.zh-CN': dmi59,
  'docs/react/use-with-vite.en-US': dmi60,
  'docs/react/use-with-vite.zh-CN': dmi61,
  'docs/spec/research-empty.en-US': dmi62,
  'docs/spec/research-empty.zh-CN': dmi63,
  'docs/blog/check-conduct.en-US': dmi64,
  'docs/blog/check-conduct.zh-CN': dmi65,
  'docs/blog/tooltip-align.en-US': dmi66,
  'docs/blog/tooltip-align.zh-CN': dmi67,
  'docs/blog/virtual-table.en-US': dmi68,
  'docs/blog/virtual-table.zh-CN': dmi69,
  'docs/react/common-props.en-US': dmi70,
  'docs/react/common-props.zh-CN': dmi71,
  'docs/react/contributing.en-US': dmi72,
  'docs/react/contributing.zh-CN': dmi73,
  'docs/react/migration-v5.en-US': dmi74,
  'docs/react/migration-v5.zh-CN': dmi75,
  'docs/react/use-with-umi.en-US': dmi76,
  'docs/react/use-with-umi.zh-CN': dmi77,
  'docs/spec/research-form.en-US': dmi78,
  'docs/spec/research-form.zh-CN': dmi79,
  'docs/spec/research-list.en-US': dmi80,
  'docs/spec/research-list.zh-CN': dmi81,
  'docs/blog/color-picker.en-US': dmi82,
  'docs/blog/color-picker.zh-CN': dmi83,
  'docs/blog/getContainer.en-US': dmi84,
  'docs/blog/getContainer.zh-CN': dmi85,
  'docs/blog/issue-helper.en-US': dmi86,
  'docs/blog/issue-helper.zh-CN': dmi87,
  'docs/blog/render-times.en-US': dmi88,
  'docs/blog/render-times.zh-CN': dmi89,
  'docs/blog/tree-shaking.en-US': dmi90,
  'docs/blog/tree-shaking.zh-CN': dmi91,
  'docs/spec/data-display.en-US': dmi92,
  'docs/spec/data-display.zh-CN': dmi93,
  'docs/spec/illustration.en-US': dmi94,
  'docs/spec/illustration.zh-CN': dmi95,
  'docs/blog/extract-ssr.en-US': dmi96,
  'docs/blog/extract-ssr.zh-CN': dmi97,
  'docs/spec/copywriting.en-US': dmi98,
  'docs/spec/copywriting.zh-CN': dmi99,
  'docs/spec/data-format.en-US': dmi100,
  'docs/spec/data-format.zh-CN': dmi101,
  'docs/spec/detail-page.en-US': dmi102,
  'docs/spec/detail-page.zh-CN': dmi103,
  'docs/spec/lightweight.en-US': dmi104,
  'docs/spec/lightweight.zh-CN': dmi105,
  'docs/blog/happy-work.en-US': dmi106,
  'docs/blog/happy-work.zh-CN': dmi107,
  'docs/react/introduce.en-US': dmi108,
  'docs/react/introduce.zh-CN': dmi109,
  'docs/spec/data-entry.en-US': dmi110,
  'docs/spec/data-entry.zh-CN': dmi111,
  'docs/spec/invitation.en-US': dmi112,
  'docs/spec/invitation.zh-CN': dmi113,
  'docs/spec/navigation.en-US': dmi114,
  'docs/spec/navigation.zh-CN': dmi115,
  'docs/spec/repetition.en-US': dmi116,
  'docs/spec/repetition.zh-CN': dmi117,
  'docs/spec/transition.en-US': dmi118,
  'docs/spec/transition.zh-CN': dmi119,
  'docs/blog/css-in-js.en-US': dmi120,
  'docs/blog/css-in-js.zh-CN': dmi121,
  'docs/spec/alignment.en-US': dmi122,
  'docs/spec/alignment.zh-CN': dmi123,
  'docs/spec/data-list.en-US': dmi124,
  'docs/spec/data-list.zh-CN': dmi125,
  'docs/spec/introduce.en-US': dmi126,
  'docs/spec/introduce.zh-CN': dmi127,
  'docs/spec/proximity.en-US': dmi128,
  'docs/spec/proximity.zh-CN': dmi129,
  'docs/blog/suspense.en-US': dmi130,
  'docs/blog/suspense.zh-CN': dmi131,
  'docs/spec/contrast.en-US': dmi132,
  'docs/spec/contrast.zh-CN': dmi133,
  'docs/spec/feedback.en-US': dmi134,
  'docs/spec/feedback.zh-CN': dmi135,
  'docs/spec/overview.en-US': dmi136,
  'docs/spec/overview.zh-CN': dmi137,
  'docs/spec/reaction.en-US': dmi138,
  'docs/spec/reaction.zh-CN': dmi139,
  'docs/spec/buttons.en-US': dmi140,
  'docs/spec/buttons.zh-CN': dmi141,
  'docs/spec/colors.en-US': dmi142,
  'docs/spec/colors.zh-CN': dmi143,
  'docs/spec/direct.en-US': dmi144,
  'docs/spec/direct.zh-CN': dmi145,
  'docs/spec/layout.en-US': dmi146,
  'docs/spec/layout.zh-CN': dmi147,
  'docs/spec/motion.en-US': dmi148,
  'docs/spec/motion.zh-CN': dmi149,
  'docs/spec/shadow.en-US': dmi150,
  'docs/spec/shadow.zh-CN': dmi151,
  'docs/spec/values.en-US': dmi152,
  'docs/spec/values.zh-CN': dmi153,
  'docs/spec/visual.en-US': dmi154,
  'docs/spec/visual.zh-CN': dmi155,
  'docs/react/i18n.en-US': dmi156,
  'docs/react/i18n.zh-CN': dmi157,
  'docs/spec/cases.en-US': dmi158,
  'docs/spec/cases.zh-CN': dmi159,
  'docs/react/faq.en-US': dmi160,
  'docs/react/faq.zh-CN': dmi161,
  'docs/resources.en-US': dmi162,
  'docs/resources.zh-CN': dmi163,
  'docs/spec/dark.en-US': dmi164,
  'docs/spec/dark.zh-CN': dmi165,
  'docs/spec/font.en-US': dmi166,
  'docs/spec/font.zh-CN': dmi167,
  'docs/spec/icon.en-US': dmi168,
  'docs/spec/icon.zh-CN': dmi169,
  'docs/spec/stay.en-US': dmi170,
  'docs/spec/stay.zh-CN': dmi171,
  'components/affix/index.en-US': dmi172,
  'components/affix/index.zh-CN': dmi173,
  'components/alert/index.en-US': dmi174,
  'components/alert/index.zh-CN': dmi175,
  'components/anchor/index.en-US': dmi176,
  'components/anchor/index.zh-CN': dmi177,
  'components/app/index.en-US': dmi178,
  'components/app/index.zh-CN': dmi179,
  'components/auto-complete/index.en-US': dmi180,
  'components/auto-complete/index.zh-CN': dmi181,
  'components/avatar/index.en-US': dmi182,
  'components/avatar/index.zh-CN': dmi183,
  'components/badge/index.en-US': dmi184,
  'components/badge/index.zh-CN': dmi185,
  'components/breadcrumb/index.en-US': dmi186,
  'components/breadcrumb/index.zh-CN': dmi187,
  'components/button/index.en-US': dmi188,
  'components/button/index.zh-CN': dmi189,
  'components/calendar/index.en-US': dmi190,
  'components/calendar/index.zh-CN': dmi191,
  'components/card/index.en-US': dmi192,
  'components/card/index.zh-CN': dmi193,
  'components/carousel/index.en-US': dmi194,
  'components/carousel/index.zh-CN': dmi195,
  'components/cascader/index.en-US': dmi196,
  'components/cascader/index.zh-CN': dmi197,
  'components/checkbox/index.en-US': dmi198,
  'components/checkbox/index.zh-CN': dmi199,
  'components/collapse/index.en-US': dmi200,
  'components/collapse/index.zh-CN': dmi201,
  'components/color-picker/index.en-US': dmi202,
  'components/color-picker/index.zh-CN': dmi203,
  'components/config-provider/index.en-US': dmi204,
  'components/config-provider/index.zh-CN': dmi205,
  'components/date-picker/index.en-US': dmi206,
  'components/date-picker/index.zh-CN': dmi207,
  'components/descriptions/index.en-US': dmi208,
  'components/descriptions/index.zh-CN': dmi209,
  'components/divider/index.en-US': dmi210,
  'components/divider/index.zh-CN': dmi211,
  'components/drawer/index.en-US': dmi212,
  'components/drawer/index.zh-CN': dmi213,
  'components/dropdown/index.en-US': dmi214,
  'components/dropdown/index.zh-CN': dmi215,
  'components/empty/index.en-US': dmi216,
  'components/empty/index.zh-CN': dmi217,
  'components/flex/index.en-US': dmi218,
  'components/flex/index.zh-CN': dmi219,
  'components/float-button/index.en-US': dmi220,
  'components/float-button/index.zh-CN': dmi221,
  'components/form/index.en-US': dmi222,
  'components/form/index.zh-CN': dmi223,
  'components/grid/index.en-US': dmi224,
  'components/grid/index.zh-CN': dmi225,
  'components/icon/index.en-US': dmi226,
  'components/icon/index.zh-CN': dmi227,
  'components/image/index.en-US': dmi228,
  'components/image/index.zh-CN': dmi229,
  'components/input-number/index.en-US': dmi230,
  'components/input-number/index.zh-CN': dmi231,
  'components/input/index.en-US': dmi232,
  'components/input/index.zh-CN': dmi233,
  'components/layout/index.en-US': dmi234,
  'components/layout/index.zh-CN': dmi235,
  'components/list/index.en-US': dmi236,
  'components/list/index.zh-CN': dmi237,
  'components/mentions/index.en-US': dmi238,
  'components/mentions/index.zh-CN': dmi239,
  'components/menu/index.en-US': dmi240,
  'components/menu/index.zh-CN': dmi241,
  'components/message/index.en-US': dmi242,
  'components/message/index.zh-CN': dmi243,
  'components/modal/index.en-US': dmi244,
  'components/modal/index.zh-CN': dmi245,
  'components/notification/index.en-US': dmi246,
  'components/notification/index.zh-CN': dmi247,
  'components/overview/index.en-US': dmi248,
  'components/overview/index.zh-CN': dmi249,
  'components/pagination/index.en-US': dmi250,
  'components/pagination/index.zh-CN': dmi251,
  'components/popconfirm/index.en-US': dmi252,
  'components/popconfirm/index.zh-CN': dmi253,
  'components/popover/index.en-US': dmi254,
  'components/popover/index.zh-CN': dmi255,
  'components/progress/index.en-US': dmi256,
  'components/progress/index.zh-CN': dmi257,
  'components/qr-code/index.en-US': dmi258,
  'components/qr-code/index.zh-CN': dmi259,
  'components/radio/index.en-US': dmi260,
  'components/radio/index.zh-CN': dmi261,
  'components/rate/index.en-US': dmi262,
  'components/rate/index.zh-CN': dmi263,
  'components/result/index.en-US': dmi264,
  'components/result/index.zh-CN': dmi265,
  'components/segmented/index.en-US': dmi266,
  'components/segmented/index.zh-CN': dmi267,
  'components/select/index.en-US': dmi268,
  'components/select/index.zh-CN': dmi269,
  'components/skeleton/index.en-US': dmi270,
  'components/skeleton/index.zh-CN': dmi271,
  'components/slider/index.en-US': dmi272,
  'components/slider/index.zh-CN': dmi273,
  'components/space/index.en-US': dmi274,
  'components/space/index.zh-CN': dmi275,
  'components/spin/index.en-US': dmi276,
  'components/spin/index.zh-CN': dmi277,
  'components/statistic/index.en-US': dmi278,
  'components/statistic/index.zh-CN': dmi279,
  'components/steps/index.en-US': dmi280,
  'components/steps/index.zh-CN': dmi281,
  'components/switch/index.en-US': dmi282,
  'components/switch/index.zh-CN': dmi283,
  'components/table/index.en-US': dmi284,
  'components/table/index.zh-CN': dmi285,
  'components/tabs/index.en-US': dmi286,
  'components/tabs/index.zh-CN': dmi287,
  'components/tag/index.en-US': dmi288,
  'components/tag/index.zh-CN': dmi289,
  'components/time-picker/index.en-US': dmi290,
  'components/time-picker/index.zh-CN': dmi291,
  'components/timeline/index.en-US': dmi292,
  'components/timeline/index.zh-CN': dmi293,
  'components/tooltip/index.en-US': dmi294,
  'components/tooltip/index.zh-CN': dmi295,
  'components/tour/index.en-US': dmi296,
  'components/tour/index.zh-CN': dmi297,
  'components/transfer/index.en-US': dmi298,
  'components/transfer/index.zh-CN': dmi299,
  'components/tree-select/index.en-US': dmi300,
  'components/tree-select/index.zh-CN': dmi301,
  'components/tree/index.en-US': dmi302,
  'components/tree/index.zh-CN': dmi303,
  'components/typography/index.en-US': dmi304,
  'components/typography/index.zh-CN': dmi305,
  'components/upload/index.en-US': dmi306,
  'components/upload/index.zh-CN': dmi307,
  'components/watermark/index.en-US': dmi308,
  'components/watermark/index.zh-CN': dmi309,
  'changelog-cn': dmi310,
  'changelog': dmi311,
  'components/date-picker/index.$tab-design.zh-CN': dmi312,
};

// Convert the demoIndex to a key-value pairs: <demoId, getter>
const demoIdMap = Object.keys(demoIndexes).reduce((total, current) => {
  const demoIndex = demoIndexes[current];
  const { ids, getter } = demoIndex;

  ids.forEach((id) => {
    total[id] = getter;
  });

  return total;
}, {});

/** Async to load demo by id */
export const getDemoById = async (id: string) => {
  const getter = demoIdMap[id];

  if (!getter) {
    return null;
  }

  const { demos }: any = await getter() || {};

  return demos?.[id];
};
