// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from 'G:/A_cloud-note-project/front/ant-design/components/date-picker/index.$tab-design.zh-CN.md';

export const tabs = {
  'components/date-picker/index.$tab-design.zh-CN': { key: 'design', title: '', titleIntlId: '', components: tab0 },
}
