// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'G:\A_cloud-note-project\front\ant-design\node_modules\dumi-plugin-color-chunk\es\component\index.js';
